"use client";

import type { CSSProperties } from "react";
import type { IconName } from "@/lib/iconNames";
import {
  Archive,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Bell,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheckBig,
  CircleHelp,
  CircleX,
  ClipboardList,
  Clock3,
  Code2,
  Copy,
  Cpu,
  Crosshair,
  Download,
  Droplet,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Flag,
  Folder,
  FolderOpen,
  FolderPlus,
  GitBranch,
  GitFork,
  Globe2,
  Grid2X2,
  GripVertical,
  Info,
  Layers3,
  List,
  ListCollapse,
  LoaderCircle,
  LockKeyhole,
  Menu,
  MessageSquarePlus,
  MessagesSquare,
  Mic,
  Minus,
  Moon,
  Network,
  PanelLeft,
  PanelRight,
  Paperclip,
  Pause,
  Pencil,
  Pin,
  Play,
  Plug,
  Plus,
  Radio,
  RefreshCw,
  RotateCcw,
  Rows3,
  Search,
  Send,
  Settings,
  ShieldAlert,
  Sparkles,
  Square,
  SquareTerminal,
  Star,
  Sun,
  Target,
  Trash2,
  Trophy,
  TriangleAlert,
  Upload,
  X,
  PanelBottom,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  Maximize2,
  Minimize2,
  Columns2,
  AlignJustify,
  WrapText,
  FoldVertical,
  UnfoldVertical,
  ChevronsUpDown,
  ChevronsDownUp,
  FolderTree,
  FileCode,
  FileDiff,
  FilePlus,
  FileMinus,
  Image,
  Monitor,
  Smartphone,
  Tablet,
  RotateCw,
  ArrowLeft,
  ZoomIn,
  ZoomOut,
  MousePointerClick,
  History,
  Command,
  Keyboard,
  ThumbsUp,
  ThumbsDown,
  SquarePen,
  Undo2,
  Link,
  Hash,
  AtSign,
  Slash,
  Brain,
  Wrench,
  Bot,
  User,
  Compass,
  SlidersHorizontal,
  Filter,
  ArrowUpDown,
  Bookmark,
  Share2,
  PinOff,
  CircleDashed,
  CheckCheck,
  ListTodo,
  MessageCircle,
  Quote,
  Zap,
  Gauge,
  Database,
  Package,
  Shield,
  GitCompare,
  GitPullRequest,
  GitCommitHorizontal,
  Braces,
  ScrollText,
  CircleStop,
  ArrowDownToLine,
  EllipsisVertical,
  Pilcrow,
  Split,
  Lightbulb,
  BookOpen,
  Timer,
  Hourglass,
  PencilLine,
  CornerDownLeft,
  FileSearch,
  TextSearch,
  Workflow,
  Activity,
  Asterisk,
  ListChecks,
  CircleDot,
  Settings2,
  Inbox,
  type LucideIcon,
} from "lucide-react";

/**
 * Project-wide adapter for the Lucide icon library.
 *
 * Feature code refers to semantic icon names while this component owns the
 * concrete Lucide glyph, size and stroke treatment. This keeps the whole deck
 * visually consistent and prevents screen-local SVG path copies.
 */
export type { IconName };

const ICONS: Record<IconName, LucideIcon> = {
  x: X,
  check: Check,
  checkCircle: CircleCheckBig,
  xCircle: CircleX,
  flag: Flag,
  stop: Square,
  crosshair: Crosshair,
  grid: Grid2X2,
  pencil: Pencil,
  radio: Radio,
  folder: Folder,
  folderOpen: FolderOpen,
  folderPlus: FolderPlus,
  file: FileText,
  pin: Pin,
  pause: Pause,
  paperclip: Paperclip,
  globe: Globe2,
  lock: LockKeyhole,
  menu: Menu,
  panel: PanelRight,
  panelLeft: PanelLeft,
  gear: Settings,
  send: Send,
  sendUp: ArrowUp,
  more: Ellipsis,
  terminal: SquareTerminal,
  cpu: Cpu,
  dot: Circle,
  loader: LoaderCircle,
  gripVertical: GripVertical,
  help: CircleHelp,
  info: Info,
  alert: TriangleAlert,
  circleAlert: CircleAlert,
  clock: Clock3,
  plug: Plug,
  bell: Bell,
  archive: Archive,
  trash: Trash2,
  download: Download,
  externalLink: ExternalLink,
  target: Target,
  play: Play,
  network: Network,
  list: List,
  listCollapse: ListCollapse,
  board: ClipboardList,
  layers: Layers3,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowUpRight: ArrowUpRight,
  rows: Rows3,
  upload: Upload,
  code: Code2,
  copy: Copy,
  search: Search,
  refresh: RefreshCw,
  retry: RotateCcw,
  plus: Plus,
  minus: Minus,
  gitBranch: GitBranch,
  gitFork: GitFork,
  newChat: MessageSquarePlus,
  messages: MessagesSquare,
  mic: Mic,
  trophy: Trophy,
  shieldAlert: ShieldAlert,
  sparkles: Sparkles,
  sun: Sun,
  moon: Moon,
  eye: Eye,
  eyeOff: EyeOff,
  droplet: Droplet,
  star: Star,
  panelBottom: PanelBottom,
  panelLeftClose: PanelLeftClose,
  panelLeftOpen: PanelLeftOpen,
  panelRightClose: PanelRightClose,
  panelRightOpen: PanelRightOpen,
  maximize: Maximize2,
  minimize: Minimize2,
  columns: Columns2,
  alignJustify: AlignJustify,
  wrapText: WrapText,
  foldVertical: FoldVertical,
  unfoldVertical: UnfoldVertical,
  chevronsUpDown: ChevronsUpDown,
  chevronsDownUp: ChevronsDownUp,
  folderTree: FolderTree,
  fileCode: FileCode,
  fileDiff: FileDiff,
  filePlus: FilePlus,
  fileMinus: FileMinus,
  image: Image,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  rotateCw: RotateCw,
  arrowLeft: ArrowLeft,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  mousePointer: MousePointerClick,
  history: History,
  command: Command,
  keyboard: Keyboard,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  edit: SquarePen,
  undo: Undo2,
  link: Link,
  hash: Hash,
  at: AtSign,
  slash: Slash,
  brain: Brain,
  wrench: Wrench,
  bot: Bot,
  user: User,
  compass: Compass,
  sliders: SlidersHorizontal,
  filter: Filter,
  sort: ArrowUpDown,
  bookmark: Bookmark,
  share: Share2,
  pinOff: PinOff,
  circleDashed: CircleDashed,
  checkCheck: CheckCheck,
  listTodo: ListTodo,
  messageCircle: MessageCircle,
  quote: Quote,
  zap: Zap,
  gauge: Gauge,
  database: Database,
  package: Package,
  shield: Shield,
  gitCompare: GitCompare,
  gitPullRequest: GitPullRequest,
  gitCommit: GitCommitHorizontal,
  braces: Braces,
  scroll: ScrollText,
  stopCircle: CircleStop,
  arrowDownToLine: ArrowDownToLine,
  moreVertical: EllipsisVertical,
  pilcrow: Pilcrow,
  split: Split,
  lightbulb: Lightbulb,
  book: BookOpen,
  timer: Timer,
  hourglass: Hourglass,
  pencilLine: PencilLine,
  cornerDownLeft: CornerDownLeft,
  fileSearch: FileSearch,
  textSearch: TextSearch,
  workflow: Workflow,
  activity: Activity,
  asterisk: Asterisk,
  listChecks: ListChecks,
  circleDot: CircleDot,
  settings2: Settings2,
  inbox: Inbox,
};

export function Icon({
  name,
  size = 16,
  className,
  style,
  title,
  filled: filledProp,
}: {
  name: IconName;
  size?: number;
  className?: string;
  style?: CSSProperties;
  title?: string;
  filled?: boolean;
}) {
  const IconComponent = ICONS[name];
  const filled = name === "dot" || Boolean(filledProp);
  const mergedClassName = className ? `muteki-icon ${className}` : "muteki-icon";
  return (
    <IconComponent
      className={mergedClassName}
      size={size}
      fill={filled ? "currentColor" : "none"}
      stroke={filled ? "none" : "currentColor"}
      strokeWidth={1.5}
      absoluteStrokeWidth
      aria-hidden={title ? undefined : true}
      aria-label={title}
      role={title ? "img" : undefined}
      data-filled={filled ? "true" : undefined}
      style={{ flex: "none", display: "inline-flex", verticalAlign: "text-bottom", ...style }}
    />
  );
}
