/** Deck initial state. Moved from events.ts. */
import type { DeckState } from "./types";

export function emptyDeck(runId: string): DeckState {
  return {
    runId,
    challengeName: "",
    challengeNameAutogen: false,
    category: "",
    target: "",
    lanes: {},
    workerPrompts: {},
    graph: { evidence: [], hypotheses: [], deadEnds: [] },
    sharedGraph: { verified: [], candidates: [] },
    reason: { goalMet: false, intents: [], audit: [] },
    insights: [],
    terminal: [],
    chat: [],
    blackboard: {
      intents: [],
      facts: [],
      observations: [],
      capabilities: [],
      accessPaths: [],
      capabilityGaps: [],
      valueReceipts: [],
      pocs: [],
      deadEnds: [],
      gatedFindings: [],
      reviewFindings: [],
      suppressedRoutes: [],
      branches: [],
      directives: [],
      flags: [],
      flagOrigins: {},
      events: [],
      reasonRuns: [],
      workers: [],
      truncated: {},
    },
    hitlRequests: [],
    runtimeEvents: [],
    controlCommands: [],
    controlGeneration: 0,
    executionGeneration: 0,
    operatorDirectives: [],
    resourceLocks: [],
    lockRequests: [],
    compactEpochs: 0,
    gauge: { zones: [], total: 0, limit: 0 },
    usd: 0,
    tokensIn: 0,
    tokensOut: 0,
    costBySolver: {},
    costHistory: {},
    started: false,
    preparing: false,
    finished: false,
    followupPending: false,
    solved: false,
    flags: [],
    invalidatedFlags: [],
    expectedFlags: 1,
    platformConfirmationRequired: false,
    flagConfirmations: [],
    expectedFindings: 1,
    multiFlag: false,
    preflightFailures: [],
    degradedEngines: {},
  };
}
