import { createRoot } from 'react-dom/client';
import { App } from './App';
import { I18nProvider } from '@/lib/i18n';
import SchemeBoot from '@/components/SchemeBoot';
import { Providers } from '@/app/providers';
import "./theme.css";
import "@/app/styles/base.css";
import "@/app/styles/shell.css";
import "@/app/styles/conversation.css";
import "@/app/styles/responsive.css";
import "@/app/styles/solve-collaboration.css";
import "@/app/styles/solve-collaboration-page.css";
import "@/app/styles/solve-orchestration.css";
import "@/app/styles/solve-runtime.css";
import "@/app/styles/solve-panels.css";
import "@/app/styles/workers-conversation.css";
import "@/app/styles/workers-inspector.css";
import "@/app/styles/workers-settings.css";
import "@/app/styles/competition-operations.css";
import "@/app/styles/competition-credentials.css";
import "@/app/styles/competition-capabilities.css";
import "@/app/styles/competition-catalog.css";
import "@/app/styles/dialogs.css";
import "@/app/styles/settings-conversation.css";
import "@/app/styles/settings-navigation.css";
import "@/app/styles/settings-drawer.css";
import "@/app/styles/settings-model-picker.css";
import "@/app/styles/settings-workspace.css";
import "@/app/styles/settings-hub.css";
import "@/app/styles/settings-notifications.css";
import "@/app/styles/settings-agents.css";
import "@/app/styles/task-worker-settings.css";
import "@/app/styles/pentest.css";
import "@/app/styles/ux.css";
import "@/app/styles/brand.css";
import "@/app/styles/chat/shell.css";
import "@/app/styles/chat/sidebar.css";
import "@/app/styles/chat/timeline.css";
import "@/app/styles/chat/markdown.css";
import "@/app/styles/chat/composer.css";
import "@/app/styles/chat/diff.css";
import "@/app/styles/chat/surfaces.css";
import "@/app/styles/chat/dialogs.css";
import "@/app/styles/chat/interaction.css";
import "@/app/styles/workspace-rail.css";
import '@/styles/transitions/_root.css';
import '@/styles/transitions/index.css';
import '@/styles/transitions/surfaces.css';
import '@/styles/transitions/accessibility.css';
import './styles.css';

createRoot(document.getElementById('root')!).render(<I18nProvider><Providers><SchemeBoot /><App /></Providers></I18nProvider>);
