// Code generated by scripts/gen_contracts_ts.py from muteki/platform/contracts. DO NOT EDIT.
// 手动修改会在下次生成时被覆盖；字段变更请改 Python 契约模型。

export const CONTRACTS_SCHEMA_VERSION = 1;

/** Thread 对话模式，决定 CapabilityBinding 的默认能力集合。 */
export type ThreadMode = "conversation" | "single_task" | "competition" | "management";

/** prepare_capability_injection 可选的能力注入方式（MCP 优先）。 */
export type InjectionKind = "mcp" | "native_tool" | "acp_mcp_config" | "agent_plugin" | "runtime_plugin" | "http_jsonrpc" | "cli_skill";

/** 统一 AgentEvent 事件类型（任务书 6.7，含 plan.updated）。 */
export type AgentEventType = "session.started" | "session.resumed" | "session.closed" | "turn.started" | "turn.completed" | "turn.failed" | "message.delta" | "message.completed" | "reasoning.summary" | "tool.started" | "tool.progress" | "tool.completed" | "approval.requested" | "approval.resolved" | "user_input.requested" | "user_input.resolved" | "artifact.created" | "workspace.changed" | "usage.updated" | "plan.updated" | "agent.updated" | "runtime.capabilities_updated" | "runtime.warning" | "runtime.error" | "runtime.exited";

/** 命令回执状态。 */
export type ReceiptState = "accepted" | "running" | "waiting" | "completed" | "failed" | "conflict" | "cancelled";

/** 外部效果执行状态；与命令接受状态分开持久化。 */
export type EffectState = "accepted" | "running" | "waiting" | "completed" | "failed" | "cancelled" | "dead_letter";

export type OutboxStatus = "pending" | "processing" | "delivered" | "failed" | "paused" | "dead_letter" | "cancelled";

/** 错误分类，调用方据此决定重试、升级或放弃。 */
export type ErrorCategory = "validation" | "permission" | "not_found" | "conflict" | "state" | "rate_limit" | "timeout" | "runtime" | "platform" | "internal";

/** 相关 Thread、Task、Workspace、设置和知识的长期作用域。 */
export interface Project {
  schema_version?: number;
  project_id?: string;
  name?: string;
  description?: string;
  settings?: Record<string, unknown>;
  created_at?: string;
  updated_at?: string;
}

/** 文件、命令、容器和 Artifact 的执行边界。 */
export interface Workspace {
  schema_version?: number;
  workspace_id?: string;
  project_id?: string | null;
  kind?: string;
  root_path?: string;
  settings?: Record<string, unknown>;
  created_at?: string;
}

/** 用户与 Muteki 的长期交互流。 */
export interface Thread {
  schema_version?: number;
  thread_id?: string;
  project_id?: string | null;
  workspace_id?: string | null;
  title?: string;
  title_source?: string;
  summary?: string;
  metadata_revision?: number;
  metadata_turn_id?: string | null;
  mode?: string;
  created_at?: string;
  updated_at?: string;
}

/** 需要完成的目标和领域输入。revision 随输入变化递增。 */
export interface Task {
  schema_version?: number;
  task_id?: string;
  thread_id?: string | null;
  project_id?: string | null;
  kind?: string;
  title?: string;
  input?: Record<string, unknown>;
  revision?: number;
  created_at?: string;
}

/** Run 的稳定引用。Run 是 Task 的稳定工作单元，身份不随重试变化。 */
export interface RunRef {
  schema_version?: number;
  run_id: string;
  task_id?: string | null;
  thread_id?: string | null;
  executor_id?: string | null;
  binding_key?: string | null;
  created_at?: string;
}

/** Run 内一次实际执行尝试，身份为 (run_id, generation)。 */
export interface ExecutionGeneration {
  schema_version?: number;
  run_id: string;
  generation: number;
  executor_id?: string | null;
  agent_session_ids?: string[];
  started_at?: string;
  ended_at?: string | null;
}

/** 一个外部 Runtime 的可恢复会话映射。 */
export interface AgentSession {
  schema_version?: number;
  agent_session_id?: string;
  external_session_id?: string | null;
  adapter_id?: string;
  runtime_instance_id?: string | null;
  thread_id?: string | null;
  run_id?: string | null;
  execution_generation?: number | null;
  resume_handle?: string | null;
  created_at?: string;
  closed_at?: string | null;
}

/** 内容寻址的不可变输入或输出，身份为 sha256。 */
export interface Artifact {
  schema_version?: number;
  sha256: string;
  name?: string;
  kind?: string;
  media_type?: string;
  size?: number;
  run_id?: string | null;
  created_at?: string;
}

/** 带 owner、scope、TTL 和 fencing token 的资源占用。 */
export interface ResourceLease {
  schema_version?: number;
  resource_kind: string;
  resource_key: string;
  owner?: string;
  scope?: string;
  ttl_seconds?: number;
  fencing_token?: number;
  acquired_at?: string;
  expires_at?: string | null;
  released_at?: string | null;
}

/** RunGateway.ensure_bound_run 的幂等请求。 */
export interface BoundRunRequest {
  schema_version?: number;
  binding_key: string;
  task_id?: string | null;
  task_kind?: string;
  task_revision?: number;
  run_id?: string | null;
  executor_id?: string | null;
  payload?: Record<string, unknown>;
}

/** 下发给单个 Run 的控制命令（start/pause/resume/resolve/stop 等）。 */
export interface RunCommand {
  schema_version?: number;
  command_type: string;
  command_id?: string;
  actor_id?: string;
  expected_generation?: number | null;
  payload?: Record<string, unknown>;
}

/** 经 RunGateway 暴露的公开 Run 事件（由现有 Run Event 适配而来）。 */
export interface RunEvent {
  schema_version?: number;
  run_id: string;
  seq?: number;
  event_type?: string;
  occurred_at?: string;
  payload?: Record<string, unknown>;
}

/** Run 当前状态快照，用于查询与恢复展示。 */
export interface RunSnapshot {
  schema_version?: number;
  run_id: string;
  state?: string;
  generation?: number;
  task_kind?: string;
  executor_id?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  detail?: Record<string, unknown>;
}

/** 交给 RunExecutor.execute 的执行上下文。 */
export interface RunExecutionContext {
  schema_version?: number;
  run_id: string;
  task_kind?: string;
  generation?: number;
  task_id?: string | null;
  workspace_id?: string | null;
  execution_binding_id?: string | null;
  payload?: Record<string, unknown>;
}

/** RunExecutor.execute 的终态结果。 */
export interface RunResult {
  schema_version?: number;
  run_id: string;
  state?: string;
  detail?: Record<string, unknown>;
}

/** Run 使用的执行器、Adapter instance、Profile、Policy 和领域能力。 */
export interface ExecutionBinding {
  schema_version?: number;
  execution_binding_id?: string;
  run_id?: string | null;
  task_id?: string | null;
  executor_id?: string;
  adapter_id?: string | null;
  runtime_instance_id?: string | null;
  profile_id?: string | null;
  policy_version?: number;
  domain_capabilities?: string[];
  created_at?: string;
  revoked_at?: string | null;
}

/** Thread 级能力授权。mode 与 tool_set 在一个 version 内不可变。 */
export interface CapabilityBinding {
  schema_version?: number;
  binding_id?: string;
  binding_version?: number;
  thread_id?: string;
  principal_id?: string;
  mode?: ThreadMode;
  tool_set?: string[];
  allowed_commands?: string[];
  allowed_queries?: string[];
  resource_scopes?: string[];
  policy_version?: number;
  created_at?: string;
  revoked_at?: string | null;
}

/** CapabilityBinding 面向具体 AgentSession 的短期授权和注入实例。 */
export interface CapabilityGrant {
  schema_version?: number;
  grant_id?: string;
  binding_id?: string;
  agent_session_id?: string;
  runtime_instance_id?: string | null;
  injection_kind?: InjectionKind;
  audience?: string;
  credential_ref?: string | null;
  issued_at?: string;
  expires_at?: string | null;
  revoked_at?: string | null;
  last_touched_at?: string | null;
}

/** 注入给 Runtime 的工具描述（名称、说明与 JSON Schema 入参）。 */
export interface ToolDescription {
  schema_version?: number;
  name: string;
  description?: string;
  input_schema?: Record<string, unknown>;
}

/** Adapter 为一次 Session 启动生成的能力注入计划。 */
export interface CapabilityInjectionPlan {
  schema_version?: number;
  injection_kind: InjectionKind;
  gateway_endpoint?: string;
  tool_descriptions?: ToolDescription[];
  credential_ref?: string | null;
  audience?: string;
  runtime_config?: Record<string, unknown>;
  binding_id?: string | null;
  grant_id?: string | null;
}

/** 一次能力调用经协议入口解析后的绑定上下文。 */
export interface BindingContext {
  schema_version?: number;
  binding_id: string;
  binding_version?: number;
  grant_id?: string | null;
  thread_id?: string;
  agent_session_id?: string | null;
  principal_id?: string;
  audience?: string;
  mode?: ThreadMode;
}

/** AgentCapabilityGateway.describe 返回的可见能力描述。 */
export interface CapabilityDescriptor {
  schema_version?: number;
  binding_id: string;
  binding_version?: number;
  mode?: ThreadMode;
  tools?: ToolDescription[];
  allowed_commands?: string[];
  allowed_queries?: string[];
  resource_scopes?: string[];
}

/** 一次能力调用请求，最终归一化为 MutekiCommandAPI 的 command/query。 */
export interface CapabilityInvocation {
  schema_version?: number;
  tool_name: string;
  invocation_id?: string;
  arguments?: Record<string, unknown>;
  correlation_id?: string | null;
  image_input?: boolean | null;
}

/** 一次能力调用的统一结果。 */
export interface CapabilityResult {
  schema_version?: number;
  ok?: boolean;
  invocation_id?: string | null;
  receipt?: CommandReceipt | null;
  result?: unknown;
  error?: ErrorEnvelope | null;
  images?: CapabilityImage[];
}

/** 随工具结果交给模型的图片（base64）；其落盘路径与 SHA-256 在 result 中。 */
export interface CapabilityImage {
  schema_version?: number;
  mime_type: string;
  data: string;
}

/** Adapter probe 得到的 Runtime 能力（任务书 6.5 全量字段）。 */
export interface AgentCapabilities {
  schema_version?: number;
  streaming?: boolean;
  resume?: boolean;
  resume_continues_turn?: boolean;
  steer?: boolean;
  interrupt?: boolean;
  approval?: boolean;
  user_input?: boolean;
  fork?: boolean;
  structured_output?: boolean;
  subagents?: boolean;
  skills?: boolean;
  mcp?: boolean;
  native_tool_binding?: boolean;
  acp_mcp_config?: boolean;
  agent_plugin?: boolean;
  runtime_plugin_binding?: boolean;
  structured_http_rpc?: boolean;
  tool_events?: boolean;
  usage_events?: boolean;
  session_persistence?: boolean;
  plan?: boolean;
  plan_mode?: boolean;
  plan_mode_per_turn?: boolean;
  image_input?: boolean;
  supported_models?: string[];
  supported_efforts?: string[];
  access_modes?: string[];
  permission_modes?: string[];
  sandbox_modes?: string[];
  compaction?: boolean;
  transport_kind?: string;
  protocol_version?: string;
  runtime_version?: string;
  capability_source?: string;
}

/** ExternalAgentAdapter.probe 的探测请求。 */
export interface ProbeRequest {
  schema_version?: number;
  runtime_instance_id?: string | null;
  include_models?: boolean;
  options?: Record<string, unknown>;
}

/** Every launch option an adapter may read from SessionStart.options. */
export interface SessionOptions {
  schema_version?: number;
  principal_id?: string | null;
  thread_mode?: ThreadMode | null;
  resource_scopes?: string[] | null;
  audience?: string | null;
  cwd?: string;
  env?: Record<string, unknown>;
  chat_tools?: ToolDescription[] | null;
  chat_control_enabled?: boolean;
  resume_prompt?: string;
  plugins?: Record<string, unknown>[];
  skills?: "all" | string[] | null;
  hooks?: Record<string, unknown>;
  allowed_tools?: string[];
  max_turns?: number | null;
  fork_session?: boolean;
  chat_native_plugins?: Record<string, unknown>[];
  chat_hook_approvals?: Record<string, unknown>;
  fork_from?: string;
  fork_last_turn_id?: string;
  role?: string;
  add_dirs?: string[];
  ephemeral?: boolean;
  session_dir?: string;
  title?: string | null;
  timeout_s?: number | null;
  web_access?: boolean;
  kb_access?: boolean;
  prompt_via_stdin?: boolean;
  solver_id?: string;
  worker_mode?: string;
  engine?: string;
}

/** 启动（或恢复）一个外部 Agent Session 的请求。 */
export interface SessionStart {
  schema_version?: number;
  agent_session_id?: string;
  thread_id?: string | null;
  run_id?: string | null;
  execution_generation?: number | null;
  workspace_id?: string | null;
  resume_handle?: string | null;
  model?: string | null;
  effort?: string | null;
  service_tier?: string | null;
  access_mode?: string | null;
  interaction_mode?: "default" | "plan";
  permission_mode?: string | null;
  sandbox_mode?: string | null;
  options?: SessionOptions;
}

/** Adapter 返回的会话引用。 */
export interface AgentSessionRef {
  schema_version?: number;
  agent_session_id: string;
  adapter_id?: string;
  external_session_id?: string | null;
  runtime_instance_id?: string | null;
  resume_handle?: string | null;
}

/** A resolved, authorized attachment ready for adapter delivery. */
export interface AttachmentRef {
  schema_version?: number;
  sha256: string;
  name?: string;
  media_type?: string;
  size?: number;
  cas_path?: string;
  path?: string;
  workspace_path?: string;
  delivery?: "native_image" | "workspace_file";
  content_base64?: string;
}

/** Structured side data of an ordinary user message. */
export interface MessagePayload {
  schema_version?: number;
  attachments?: AttachmentRef[];
  capability_context?: string;
  runtime_capability?: Record<string, unknown>;
  runtime_command_arguments?: string;
  client_user_message_id?: string;
  interaction_mode?: "default" | "plan";
}

export interface SteerPayload {
  schema_version?: number;
  expected_turn_id?: string;
  client_user_message_id?: string;
  capability_revision?: number | null;
  attachments?: AttachmentRef[];
}

export interface ApprovalResponsePayload {
  schema_version?: number;
  approval_id: string;
  decision: "allow" | "deny";
  scope?: "once" | "session";
  note?: string;
  option_id?: string;
  updated_input?: Record<string, unknown> | null;
}

export interface UserInputResponsePayload {
  schema_version?: number;
  request_id: string;
  decision?: "submit" | "decline" | "cancel";
  answers?: Record<string, unknown>;
}

/** An ordinary user message that starts a new turn. */
export interface MessageInput {
  schema_version?: number;
  kind?: "message";
  text?: string;
  payload?: MessagePayload;
}

/** Extra guidance appended to the running turn. */
export interface SteerInput {
  schema_version?: number;
  kind?: "steer";
  text?: string;
  payload?: SteerPayload;
}

/** Operator verdict for a pending approval request. */
export interface ApprovalResponseInput {
  schema_version?: number;
  kind?: "approval_response";
  text?: string;
  payload: ApprovalResponsePayload;
}

/** Operator answers for a pending user-input request. */
export interface UserInputResponseInput {
  schema_version?: number;
  kind?: "user_input_response";
  text?: string;
  payload: UserInputResponsePayload;
}

/** 统一 AgentEvent（任务书 6.7）。 */
export interface AgentEvent {
  schema_version?: number;
  event_type: AgentEventType;
  agent_session_id?: string;
  external_session_id?: string | null;
  run_id?: string | null;
  execution_generation?: number | null;
  turn_id?: string | null;
  seq?: number;
  occurred_at?: string;
  native_type?: string | null;
  payload?: Record<string, unknown>;
}

/** Agent Session 当前状态快照。 */
export interface AgentSessionSnapshot {
  schema_version?: number;
  agent_session_id: string;
  adapter_id?: string;
  external_session_id?: string | null;
  state?: string;
  current_turn_id?: string | null;
  pending_approval?: Record<string, unknown> | null;
  pending_user_input?: Record<string, unknown> | null;
  usage?: Record<string, unknown>;
  last_event_seq?: number;
}

/** 命令发起方，例如 {"kind": "operator", "id": "local-user"}。 */
export interface ActorRef {
  schema_version?: number;
  kind?: string;
  id?: string;
  binding_id?: string;
  binding_version?: number | null;
  thread_id?: string;
}

/** typed command 信封（任务书 6.1 JSON）。 */
export interface CommandEnvelope {
  schema_version?: number;
  command_id?: string;
  command_type?: string;
  aggregate_type?: string;
  aggregate_id?: string;
  expected_version?: number | null;
  actor?: ActorRef;
  idempotency_key?: string | null;
  payload?: Record<string, unknown>;
}

/** 只读查询信封。查询不产生事件，但走同一授权边界。 */
export interface QueryEnvelope {
  schema_version?: number;
  query_id?: string;
  query_type?: string;
  aggregate_type?: string | null;
  aggregate_id?: string | null;
  actor?: ActorRef;
  params?: Record<string, unknown>;
}

/** 按 aggregate 流读取事件。cursor 是绑定流与授权范围的不透明值。 */
export interface EventReadRequest {
  schema_version?: number;
  aggregate_type: string;
  aggregate_id: string;
  after_cursor?: string | null;
  limit?: number;
}

/** 有界等待：到达服务端上限时返回 timeout 和最新 cursor。 */
export interface WaitRequest {
  schema_version?: number;
  aggregate_type: string;
  aggregate_id: string;
  after_cursor?: string | null;
  timeout_seconds?: number;
  limit?: number;
}

/** 查询结果。result 为完整投影数据。 */
export interface QueryResult {
  schema_version?: number;
  query_id?: string | null;
  query_type?: string;
  result?: unknown;
  cursor?: string | null;
}

/** 一页事件。next_cursor 仅在还有后续事件时返回。 */
export interface EventPage {
  schema_version?: number;
  events?: EventEnvelope[];
  next_cursor?: string | null;
}

/** 有界 wait 的结果：新事件或 timeout（附带最新 cursor）。 */
export interface WaitResult {
  schema_version?: number;
  state?: string;
  events?: EventEnvelope[];
  cursor?: string | null;
}

/** 新增领域事件的统一 envelope（任务书 6.1 JSON）。 */
export interface EventEnvelope {
  schema_version?: number;
  event_id?: string;
  aggregate_type?: string;
  aggregate_id?: string;
  stream_seq?: number;
  event_type?: string;
  occurred_at?: string;
  producer?: string;
  actor_id?: string;
  command_id?: string | null;
  causation_id?: string | null;
  correlation_id?: string | null;
  idempotency_key?: string | null;
  payload?: Record<string, unknown>;
}

/** 面向 SSE/WebSocket/AG-UI 的完整公开事件。 */
export interface PublicEvent {
  schema_version?: number;
  event_id?: string;
  aggregate_type?: string;
  aggregate_id?: string;
  stream_seq?: number;
  event_type?: string;
  occurred_at?: string;
  producer?: string;
  actor_id?: string;
  command_id?: string | null;
  causation_id?: string | null;
  correlation_id?: string | null;
  idempotency_key?: string | null;
  payload?: Record<string, unknown>;
}

/** 命令作用的聚合引用，例如 {"type": "run", "id": "run_..."}。 */
export interface AggregateRef {
  schema_version?: number;
  type?: string;
  id?: string;
}

/** 命令接收回执（任务书 6.2 JSON）。 */
export interface CommandReceipt {
  schema_version?: number;
  command_id: string;
  receipt_id?: string;
  state?: ReceiptState;
  run_id?: string | null;
  aggregate?: AggregateRef | null;
  event_cursor?: string | null;
  deduplicated?: boolean;
  submitted_at?: string;
  next?: string[];
  output?: Record<string, unknown>;
  effect_ids?: string[];
  error?: ErrorEnvelope | null;
}

/** 命令产生的一项可重试外部效果的持久回执。 */
export interface EffectReceipt {
  schema_version?: number;
  effect_id?: string;
  command_id: string;
  acceptance_receipt_id?: string;
  domain?: string;
  state?: EffectState;
  aggregate?: AggregateRef | null;
  correlation_id?: string;
  outbox_id?: string;
  destination?: string;
  idempotency_key?: string;
  attempts?: number;
  max_attempts?: number;
  retry_after?: string | null;
  object_links?: Record<string, unknown>;
  output?: Record<string, unknown>;
  error?: ErrorEnvelope | null;
  created_at?: string;
  updated_at?: string;
  completed_at?: string | null;
}

/** 持久 outbox 记录。 */
export interface OutboxRecord {
  schema_version?: number;
  outbox_id?: string;
  command_id?: string | null;
  effect_id?: string | null;
  correlation_id?: string;
  idempotency_key?: string;
  event_id?: string | null;
  aggregate_type?: string;
  aggregate_id?: string;
  event_type?: string;
  destination?: string;
  status?: OutboxStatus;
  attempts?: number;
  payload?: Record<string, unknown>;
  created_at?: string;
  delivered_at?: string | null;
  last_error?: string | null;
}

/** 写入图服务的一条事件。 */
export interface GraphEvent {
  schema_version?: number;
  graph_id?: string;
  event_type?: string;
  actor_id?: string;
  occurred_at?: string;
  idempotency_key?: string | null;
  payload?: Record<string, unknown>;
}

/** append 的接收回执。 */
export interface GraphReceipt {
  schema_version?: number;
  graph_id?: string;
  event_id?: string;
  stream_seq?: number;
  deduplicated?: boolean;
}

/** snapshot 的读取范围，例如某条 branch、某类 fact。 */
export interface GraphScope {
  schema_version?: number;
  graph_id: string;
  scope?: Record<string, unknown>;
}

/** 图状态快照（已投影的读取模型）。 */
export interface GraphSnapshot {
  schema_version?: number;
  graph_id: string;
  watermark?: number;
  state?: Record<string, unknown>;
}

/** 原子领取一个开放 Intent（或等价工作项）。 */
export interface ClaimRequest {
  schema_version?: number;
  graph_id: string;
  intent_id: string;
  claimant?: string;
  ttl_seconds?: number;
}

export interface ClaimReceipt {
  schema_version?: number;
  granted?: boolean;
  graph_id?: string;
  intent_id?: string;
  claimant?: string;
  fencing_token?: number;
  expires_at?: string | null;
}

/** 申请一个图内独占资源（端口、监听器、目标会话等）的租约。 */
export interface LeaseRequest {
  schema_version?: number;
  graph_id: string;
  resource_kind: string;
  resource_key: string;
  owner?: string;
  ttl_seconds?: number;
}

export interface LeaseReceipt {
  schema_version?: number;
  granted?: boolean;
  graph_id?: string;
  resource_kind?: string;
  resource_key?: string;
  owner?: string;
  fencing_token?: number;
  expires_at?: string | null;
}

/** 领域模块声明（任务书 6.8 字段清单）。 */
export interface DomainModuleDescriptor {
  schema_version?: number;
  id?: string;
  version?: string;
  task_kinds?: string[];
  required_capabilities?: string[];
  default_executor?: string;
  command_handlers?: Record<string, unknown>;
  event_namespaces?: string[];
  api_routes?: string[];
  workspace_kind?: string;
  ui_contributions?: Record<string, unknown>;
  artifact_types?: string[];
  graph_binding?: string | null;
  gate_binding?: string | null;
}

/** 一个比赛平台连接的引用；真实凭据在 SecretStore，不进入本模型。 */
export interface PlatformConnectionRef {
  schema_version?: number;
  connection_id?: string;
  platform_kind?: string;
  endpoint?: string;
  competition_id?: string | null;
}

/** 平台能力探测结果。 */
export interface PlatformCapabilities {
  schema_version?: number;
  platform_kind?: string;
  sync?: boolean;
  artifacts?: boolean;
  dynamic_instances?: boolean;
  submit?: boolean;
  scoreboard?: boolean;
  detail?: Record<string, unknown>;
}

export interface SyncRequest {
  schema_version?: number;
  connection_id?: string;
  competition_id?: string | null;
  cursor?: string | null;
}

export interface SyncResult {
  schema_version?: number;
  connection_id?: string;
  cursor?: string | null;
  synced_challenges?: number;
  detail?: Record<string, unknown>;
}

/** 远端题目附件引用。 */
export interface RemoteArtifactRef {
  schema_version?: number;
  connection_id?: string;
  remote_id?: string;
  url?: string;
  sha256?: string | null;
}

/** 抓取回来的 Artifact 内容（content 为原始字节）。 */
export interface ArtifactObject {
  schema_version?: number;
  sha256?: string;
  media_type?: string;
  content?: string;
}

export interface PlatformChallengeRef {
  schema_version?: number;
  connection_id?: string;
  challenge_key?: string;
  revision?: number;
}

/** 动态实例租约引用。 */
export interface InstanceLeaseRef {
  schema_version?: number;
  lease_id?: string;
  connection_id?: string;
  challenge_key?: string;
  fencing_token?: number;
  expires_at?: string | null;
}

export interface InstanceResult {
  schema_version?: number;
  lease?: InstanceLeaseRef;
  endpoints?: Record<string, unknown>;
  acquired_at?: string;
}

export interface SubmissionRequest {
  schema_version?: number;
  connection_id?: string;
  challenge_key?: string;
  flag?: string | null;
  artifact_sha256?: string | null;
  idempotency_key?: string | null;
  payload?: Record<string, unknown>;
}

export interface SubmissionResult {
  schema_version?: number;
  submission_id?: string | null;
  status?: string;
  detail?: Record<string, unknown>;
}

/** 扩展宿主入口，例如 subprocess + serve 命令。 */
export interface ExtensionEntrypoint {
  schema_version?: number;
  host?: string;
  command?: string[];
}

/** 扩展提供的能力，例如 external-agent-adapter / platform-adapter。 */
export interface ExtensionProvide {
  schema_version?: number;
  type?: string;
  id?: string;
  api_version?: number;
}

/** 扩展依赖的平台能力。 */
export interface ExtensionRequire {
  schema_version?: number;
  capability?: string;
  version?: number;
}

/** 扩展声明式权限：文件系统、网络、secret 引用与可写事件命名空间。 */
export interface ExtensionPermissions {
  schema_version?: number;
  filesystem?: string[];
  network?: string[];
  secrets?: string[];
  events_write?: string[];
}

/** 从 Agent Plugins 根清单解析出的 Muteki 客户端扩展视图。 */
export interface ExtensionManifest {
  schema_version?: number;
  plugin_schema?: string;
  client_namespace?: string;
  manifest_version?: number;
  id?: string;
  plugin_version?: string;
  version?: string;
  description?: string;
  author?: Record<string, unknown>;
  homepage?: string;
  repository?: string;
  license?: string;
  keywords?: string[];
  requires_core?: string;
  origin?: string;
  retain_previous_versions?: boolean;
  entrypoints?: ExtensionEntrypoint;
  provides?: ExtensionProvide[];
  requires?: ExtensionRequire[];
  permissions?: ExtensionPermissions;
  config_schema?: string | null;
  state_schema?: string | null;
  ui?: string | null;
}

/** 统一错误 envelope。 */
export interface ErrorEnvelope {
  schema_version?: number;
  code: string;
  message: string;
  category?: ErrorCategory;
  recovery_hint?: string;
  correlation_id?: string | null;
  retryable?: boolean;
  detail?: Record<string, unknown>;
}
