// Code generated by scripts/gen_openapi.py. DO NOT EDIT.
export const OPENAPI_SHA256 = "cb1ec6c706ef6a7c098dbc58abb4a0137afe76d618a2d9a4186b8b5deda482d1" as const;

export namespace OpenApiSchemas {
  export type Body_upload_api_threads__thread_id__uploads_post = { "command_id"?: string; "file": string; "idempotency_key"?: string };
  export type Body_upload_files_api_runs__run_id__uploads_post = { "files": Array<string> };
  export type BrowserStorageStateBody = { "command_id"?: string; "expires_at"?: string; "idempotency_key"?: string; "renew"?: boolean; "storage_state"?: { [key: string]: unknown } };
  export type CompetitionMessageBody = { "author"?: string; "command"?: { [key: string]: unknown } | null; "command_id"?: string; "idempotency_key"?: string; "text"?: string };
  export type CompetitionUnregisterBody = { "command_id"?: string; "confirm"?: boolean; "idempotency_key"?: string };
  export type ComponentStatus = { "available"?: boolean; "detail"?: string; "module_path"?: string; "name"?: string; "required"?: boolean; "schema_version"?: number };
  export type ComposerCapabilitiesBody = { "adapter_id"?: string; "project_id"?: string; "query"?: string; "thread_id"?: string; "trigger": string; "workspace_id"?: string };
  export type ConnectionProbeBody = { "command_id"?: string; "idempotency_key"?: string };
  export type ConnectionUnregisterBody = { "command_id"?: string; "confirm"?: boolean; "idempotency_key"?: string };
  export type CreateCompetitionBody = { "command_id"?: string; "connection_id": string; "description"?: string; "ends_at"?: string; "external_competition_id": string; "idempotency_key"?: string; "starts_at"?: string; "title"?: string };
  export type CreatePlatformConnectionBody = { "account_key": string; "base_url": string; "command_id"?: string; "credential"?: string | null; "credential_key"?: string; "credential_ref"?: string; "idempotency_key"?: string; "platform"?: string; "platform_kind"?: string };
  export type DomainModuleDescriptor = { "api_routes"?: Array<string>; "artifact_types"?: Array<string>; "command_handlers"?: { [key: string]: unknown }; "default_executor"?: string; "event_namespaces"?: Array<string>; "gate_binding"?: string | null; "graph_binding"?: string | null; "id"?: string; "required_capabilities"?: Array<string>; "schema_version"?: number; "task_kinds"?: Array<string>; "ui_contributions"?: { [key: string]: unknown }; "version"?: string; "workspace_kind"?: string };
  export type EffectActionBody = { "command_id"?: string; "confirm"?: boolean; "idempotency_key"?: string };
  export type EnableRequest = { "config"?: { [key: string]: unknown } | null; "version"?: string | null };
  export type ErrorCategory = "validation" | "permission" | "not_found" | "conflict" | "state" | "rate_limit" | "timeout" | "runtime" | "platform" | "internal";
  export type ErrorEnvelope = { "category"?: OpenApiSchemas.ErrorCategory; "code": string; "correlation_id"?: string | null; "detail"?: { [key: string]: unknown }; "message": string; "recovery_hint"?: string; "retryable"?: boolean; "schema_version"?: number };
  export type ExtensionSourceRequest = { "catalog_root"?: string; "extension_id"?: string; "kind": string; "path"?: string; "ref"?: string; "sha256"?: string; "url"?: string; "version"?: string };
  export type HTTPValidationError = { "detail"?: Array<OpenApiSchemas.ValidationError> };
  export type InstallRequest = { "confirmations"?: Array<string>; "preview_id"?: string; "source": OpenApiSchemas.ExtensionSourceRequest };
  export type InvokeBody = { "command_type": string; "params"?: { [key: string]: unknown } };
  export type InvokeRequest = { "command_type": string; "params"?: { [key: string]: unknown } };
  export type MaintenanceApplyBody = { "candidate_ids"?: Array<string>; "confirm": boolean };
  export type MemoryDeleteBody = { "command_id"?: string; "confirm": boolean; "idempotency_key"?: string; "reason"?: string };
  export type MemoryRecordBody = { "command_id"?: string; "consent": boolean; "content": string; "idempotency_key"?: string; "kind"?: string };
  export type ModuleRegistration = { "components"?: Array<OpenApiSchemas.ComponentStatus>; "descriptor"?: OpenApiSchemas.DomainModuleDescriptor; "error"?: OpenApiSchemas.ErrorEnvelope | null; "origin"?: string; "pending_components"?: Array<string>; "schema_version"?: number; "state"?: OpenApiSchemas.ModuleState };
  export type ModuleState = "registered" | "ready" | "unavailable" | "disabled";
  export type PlatformSecretRevokeBody = { "command_id"?: string; "confirm"?: boolean; "idempotency_key"?: string };
  export type PlatformSecretWriteBody = { "command_id"?: string; "credential": string; "expires_at"?: string; "idempotency_key"?: string; "key"?: string; "mode"?: "update" | "rotate" };
  export type PreviewRequest = { "extension_id"?: string; "source": OpenApiSchemas.ExtensionSourceRequest };
  export type ProjectGitCheckoutBody = { "branch": string; "create"?: boolean };
  export type RollbackRequest = { "version"?: string | null };
  export type ShareCreateRequest = { "access_mode": "authenticated" | "link"; "expires_in_seconds": number; "preview_id": string };
  export type SharePreviewRequest = { "attachment_ids"?: Array<string>; "include_tool_summaries"?: boolean; "message_ids"?: Array<string> | null; "redact_paths"?: boolean };
  export type TerminalSessionCreateBody = { "cols"?: number; "name"?: string; "rows"?: number };
  export type ThreadGitCheckoutBody = { "branch": string; "create"?: boolean };
  export type UninstallRequest = { "confirm"?: boolean; "preserve_artifacts"?: boolean; "preserve_logs"?: boolean; "preserve_state"?: boolean };
  export type UpgradeRequest = { "config"?: { [key: string]: unknown } | null; "confirmations"?: Array<string>; "preview_id"?: string; "source": OpenApiSchemas.ExtensionSourceRequest };
  export type ValidationError = { "ctx"?: {  }; "input"?: unknown; "loc": Array<string | number>; "msg": string; "type": string };
  export type WorkspaceCommandBody = { "command": string };
  export type WorkspaceDeleteWorktreeBody = { "command_id"?: string; "force"?: boolean; "idempotency_key"?: string; "workspace_id": string };
  export type WorkspaceKindInfo = { "aggregate_type"?: string; "create_entry"?: string; "description"?: string; "icon"?: string; "id"?: string; "module_id"?: string; "route"?: string; "schema_version"?: number; "state"?: OpenApiSchemas.ModuleState; "task_kinds"?: Array<string>; "title"?: string };
}

export interface OpenApiOperations {
  "list_runtimes_api_agent_runtimes_get": {
    method: "GET";
    path: "/api/agent-runtimes";
    pathParams: {  };
    query: { "adapter_id"?: string; "discovered"?: boolean; "transport"?: string };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "upsert_runtime_api_agent_runtimes_post": {
    method: "POST";
    path: "/api/agent-runtimes";
    pathParams: {  };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_worker_profiles_api_agent_runtimes_profiles_get": {
    method: "GET";
    path: "/api/agent-runtimes/profiles";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "upsert_profile_api_agent_runtimes_profiles_post": {
    method: "POST";
    path: "/api/agent-runtimes/profiles";
    pathParams: {  };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "remove_profile_api_agent_runtimes_profiles__name__delete": {
    method: "DELETE";
    path: "/api/agent-runtimes/profiles/{name}";
    pathParams: { "name": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "refresh_runtimes_api_agent_runtimes_refresh_post": {
    method: "POST";
    path: "/api/agent-runtimes/refresh";
    pathParams: {  };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "remove_runtime_api_agent_runtimes__instance_key__delete": {
    method: "DELETE";
    path: "/api/agent-runtimes/{instance_key}";
    pathParams: { "instance_key": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "get_runtime_api_agent_runtimes__instance_key__get": {
    method: "GET";
    path: "/api/agent-runtimes/{instance_key}";
    pathParams: { "instance_key": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "refresh_runtime_auth_api_agent_runtimes__instance_key__auth_refresh_post": {
    method: "POST";
    path: "/api/agent-runtimes/{instance_key}/auth-refresh";
    pathParams: { "instance_key": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "refresh_runtime_capabilities_api_agent_runtimes__instance_key__capability_refresh_post": {
    method: "POST";
    path: "/api/agent-runtimes/{instance_key}/capability-refresh";
    pathParams: { "instance_key": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "login_runtime_api_agent_runtimes__instance_key__login_post": {
    method: "POST";
    path: "/api/agent-runtimes/{instance_key}/login";
    pathParams: { "instance_key": string };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "logout_runtime_api_agent_runtimes__instance_key__logout_post": {
    method: "POST";
    path: "/api/agent-runtimes/{instance_key}/logout";
    pathParams: { "instance_key": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "probe_runtime_api_agent_runtimes__instance_key__probe_post": {
    method: "POST";
    path: "/api/agent-runtimes/{instance_key}/probe";
    pathParams: { "instance_key": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "auth_login_api_auth_login_post": {
    method: "POST";
    path: "/api/auth/login";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "auth_me_api_auth_me_get": {
    method: "GET";
    path: "/api/auth/me";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "auth_ticket_api_auth_ticket_post": {
    method: "POST";
    path: "/api/auth/ticket";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "capability_http_get_api_capability_get": {
    method: "GET";
    path: "/api/capability";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "capability_http_post_api_capability_post": {
    method: "POST";
    path: "/api/capability";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "overview_api_capability_management_get": {
    method: "GET";
    path: "/api/capability-management";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "update_resource_api_capability_management_resources__kind___resource_id__put": {
    method: "PUT";
    path: "/api/capability-management/resources/{kind}/{resource_id}";
    pathParams: { "kind": string; "resource_id": string };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "replace_binding_api_capability_management_threads__thread_id__binding_put": {
    method: "PUT";
    path: "/api/capability-management/threads/{thread_id}/binding";
    pathParams: { "thread_id": string };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "revoke_binding_group_api_capability_management_threads__thread_id__revoke_post": {
    method: "POST";
    path: "/api/capability-management/threads/{thread_id}/revoke";
    pathParams: { "thread_id": string };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "dispatch_api_commands_post": {
    method: "POST";
    path: "/api/commands";
    pathParams: {  };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_competitions_api_competitions_get": {
    method: "GET";
    path: "/api/competitions";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "create_competition_api_competitions_post": {
    method: "POST";
    path: "/api/competitions";
    pathParams: {  };
    query: {  };
    body: OpenApiSchemas.CreateCompetitionBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "unregister_competition_api_competitions__competition_id__delete": {
    method: "DELETE";
    path: "/api/competitions/{competition_id}";
    pathParams: { "competition_id": string };
    query: {  };
    body: OpenApiSchemas.CompetitionUnregisterBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "get_competition_api_competitions__competition_id__get": {
    method: "GET";
    path: "/api/competitions/{competition_id}";
    pathParams: { "competition_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_challenges_api_competitions__competition_id__challenges_get": {
    method: "GET";
    path: "/api/competitions/{competition_id}/challenges";
    pathParams: { "competition_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "post_command_api_competitions__competition_id__commands_post": {
    method: "POST";
    path: "/api/competitions/{competition_id}/commands";
    pathParams: { "competition_id": string };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "competition_events_api_competitions__competition_id__events_get": {
    method: "GET";
    path: "/api/competitions/{competition_id}/events";
    pathParams: { "competition_id": string };
    query: { "after"?: number };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "competition_history_api_competitions__competition_id__events_history_get": {
    method: "GET";
    path: "/api/competitions/{competition_id}/events/history";
    pathParams: { "competition_id": string };
    query: { "before"?: number | null; "limit"?: number };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_leases_api_competitions__competition_id__leases_get": {
    method: "GET";
    path: "/api/competitions/{competition_id}/leases";
    pathParams: { "competition_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "post_message_api_competitions__competition_id__messages_post": {
    method: "POST";
    path: "/api/competitions/{competition_id}/messages";
    pathParams: { "competition_id": string };
    query: {  };
    body: OpenApiSchemas.CompetitionMessageBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_submissions_api_competitions__competition_id__submissions_get": {
    method: "GET";
    path: "/api/competitions/{competition_id}/submissions";
    pathParams: { "competition_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "read_api_conversation_shares__share_id__get": {
    method: "GET";
    path: "/api/conversation-shares/{share_id}";
    pathParams: { "share_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "attachment_api_conversation_shares__share_id__attachments__attachment_id__get": {
    method: "GET";
    path: "/api/conversation-shares/{share_id}/attachments/{attachment_id}";
    pathParams: { "share_id": string; "attachment_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "composer_capabilities_api_conversation_composer_capabilities_post": {
    method: "POST";
    path: "/api/conversation/composer-capabilities";
    pathParams: {  };
    query: {  };
    body: OpenApiSchemas.ComposerCapabilitiesBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "select_directory_api_directories_select_post": {
    method: "POST";
    path: "/api/directories/select";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "dispatch_parse_preflight_api_dispatch_parse_post": {
    method: "POST";
    path: "/api/dispatch/parse";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "list_domain_modules_api_domain_modules_get": {
    method: "GET";
    path: "/api/domain-modules";
    pathParams: {  };
    query: {  };
    body: never;
    response: Array<OpenApiSchemas.ModuleRegistration>;
  };
  "get_domain_module_api_domain_modules__module_id__get": {
    method: "GET";
    path: "/api/domain-modules/{module_id}";
    pathParams: { "module_id": string };
    query: {  };
    body: never;
    response: OpenApiSchemas.ModuleRegistration | OpenApiSchemas.HTTPValidationError;
  };
  "change_domain_module_api_domain_modules__module_id___action__post": {
    method: "POST";
    path: "/api/domain-modules/{module_id}/{action}";
    pathParams: { "module_id": string; "action": string };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_effects_api_effects_get": {
    method: "GET";
    path: "/api/effects";
    pathParams: {  };
    query: { "state"?: string; "limit"?: number };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "get_effect_api_effects__effect_id__get": {
    method: "GET";
    path: "/api/effects/{effect_id}";
    pathParams: { "effect_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "cancel_effect_api_effects__effect_id__cancel_post": {
    method: "POST";
    path: "/api/effects/{effect_id}/cancel";
    pathParams: { "effect_id": string };
    query: {  };
    body: OpenApiSchemas.EffectActionBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "retry_effect_api_effects__effect_id__retry_post": {
    method: "POST";
    path: "/api/effects/{effect_id}/retry";
    pathParams: { "effect_id": string };
    query: {  };
    body: OpenApiSchemas.EffectActionBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "engines_api_engines_get": {
    method: "GET";
    path: "/api/engines";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "engines_health_api_engines_health_get": {
    method: "GET";
    path: "/api/engines/health";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "read_events_api_events_read_post": {
    method: "POST";
    path: "/api/events/read";
    pathParams: {  };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "wait_api_events_wait_post": {
    method: "POST";
    path: "/api/events/wait";
    pathParams: {  };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_extensions_api_extensions_get": {
    method: "GET";
    path: "/api/extensions";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "catalog_api_extensions_catalog_get": {
    method: "GET";
    path: "/api/extensions/catalog";
    pathParams: {  };
    query: { "root"?: string; "q"?: string };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "install_api_extensions_install_post": {
    method: "POST";
    path: "/api/extensions/install";
    pathParams: {  };
    query: {  };
    body: OpenApiSchemas.InstallRequest;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "overview_api_extensions_overview_get": {
    method: "GET";
    path: "/api/extensions/overview";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "preview_api_extensions_preview_post": {
    method: "POST";
    path: "/api/extensions/preview";
    pathParams: {  };
    query: {  };
    body: OpenApiSchemas.PreviewRequest;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "uninstall_api_extensions__extension_id__delete": {
    method: "DELETE";
    path: "/api/extensions/{extension_id}";
    pathParams: { "extension_id": string };
    query: {  };
    body: OpenApiSchemas.UninstallRequest | null;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "get_extension_api_extensions__extension_id__get": {
    method: "GET";
    path: "/api/extensions/{extension_id}";
    pathParams: { "extension_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "detail_api_extensions__extension_id__detail_get": {
    method: "GET";
    path: "/api/extensions/{extension_id}/detail";
    pathParams: { "extension_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "disable_api_extensions__extension_id__disable_post": {
    method: "POST";
    path: "/api/extensions/{extension_id}/disable";
    pathParams: { "extension_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "enable_api_extensions__extension_id__enable_post": {
    method: "POST";
    path: "/api/extensions/{extension_id}/enable";
    pathParams: { "extension_id": string };
    query: {  };
    body: OpenApiSchemas.EnableRequest;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "extension_health_api_extensions__extension_id__health_get": {
    method: "GET";
    path: "/api/extensions/{extension_id}/health";
    pathParams: { "extension_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "health_refresh_api_extensions__extension_id__health_refresh_post": {
    method: "POST";
    path: "/api/extensions/{extension_id}/health/refresh";
    pathParams: { "extension_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "invoke_api_extensions__extension_id__invoke_post": {
    method: "POST";
    path: "/api/extensions/{extension_id}/invoke";
    pathParams: { "extension_id": string };
    query: {  };
    body: OpenApiSchemas.InvokeRequest;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "extension_logs_api_extensions__extension_id__logs_get": {
    method: "GET";
    path: "/api/extensions/{extension_id}/logs";
    pathParams: { "extension_id": string };
    query: { "limit"?: number };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "logs_page_api_extensions__extension_id__logs_page_get": {
    method: "GET";
    path: "/api/extensions/{extension_id}/logs/page";
    pathParams: { "extension_id": string };
    query: { "offset"?: number; "limit"?: number };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "extension_projection_api_extensions__extension_id__projection_get": {
    method: "GET";
    path: "/api/extensions/{extension_id}/projection";
    pathParams: { "extension_id": string };
    query: { "name"?: string };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "rollback_api_extensions__extension_id__rollback_post": {
    method: "POST";
    path: "/api/extensions/{extension_id}/rollback";
    pathParams: { "extension_id": string };
    query: {  };
    body: OpenApiSchemas.RollbackRequest;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "ui_contributions_api_extensions__extension_id__ui_get": {
    method: "GET";
    path: "/api/extensions/{extension_id}/ui";
    pathParams: { "extension_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "upgrade_api_extensions__extension_id__upgrade_post": {
    method: "POST";
    path: "/api/extensions/{extension_id}/upgrade";
    pathParams: { "extension_id": string };
    query: {  };
    body: OpenApiSchemas.UpgradeRequest;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_folders_api_folders_get": {
    method: "GET";
    path: "/api/folders";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "create_folder_api_folders_post": {
    method: "POST";
    path: "/api/folders";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "delete_folder_api_folders__folder_id__delete": {
    method: "DELETE";
    path: "/api/folders/{folder_id}";
    pathParams: { "folder_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "update_folder_api_folders__folder_id__patch": {
    method: "PATCH";
    path: "/api/folders/{folder_id}";
    pathParams: { "folder_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "health_api_health_get": {
    method: "GET";
    path: "/api/health";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "import_apply_api_import_apply_post": {
    method: "POST";
    path: "/api/import/apply";
    pathParams: {  };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "import_scan_api_import_scan_get": {
    method: "GET";
    path: "/api/import/scan";
    pathParams: {  };
    query: { "adapter"?: string; "path"?: string; "limit"?: number };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "diagnostic_bundle_api_operations_diagnostic_bundle_get": {
    method: "GET";
    path: "/api/operations/diagnostic-bundle";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "maintenance_api_operations_maintenance_post": {
    method: "POST";
    path: "/api/operations/maintenance";
    pathParams: {  };
    query: {  };
    body: OpenApiSchemas.MaintenanceApplyBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "maintenance_preview_api_operations_maintenance_preview_get": {
    method: "GET";
    path: "/api/operations/maintenance-preview";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "outbox_api_operations_outbox_get": {
    method: "GET";
    path: "/api/operations/outbox";
    pathParams: {  };
    query: { "limit"?: number };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "overview_api_operations_overview_get": {
    method: "GET";
    path: "/api/operations/overview";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "receipt_api_operations_receipts__command_id__get": {
    method: "GET";
    path: "/api/operations/receipts/{command_id}";
    pathParams: { "command_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "recovery_preview_api_operations_recovery_preview_get": {
    method: "GET";
    path: "/api/operations/recovery-preview";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "list_connections_api_platform_connections_get": {
    method: "GET";
    path: "/api/platform-connections";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "create_connection_api_platform_connections_post": {
    method: "POST";
    path: "/api/platform-connections";
    pathParams: {  };
    query: {  };
    body: OpenApiSchemas.CreatePlatformConnectionBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "unregister_connection_api_platform_connections__connection_id__delete": {
    method: "DELETE";
    path: "/api/platform-connections/{connection_id}";
    pathParams: { "connection_id": string };
    query: {  };
    body: OpenApiSchemas.ConnectionUnregisterBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "revoke_browser_session_api_platform_connections__connection_id__browser_session_delete": {
    method: "DELETE";
    path: "/api/platform-connections/{connection_id}/browser-session";
    pathParams: { "connection_id": string };
    query: {  };
    body: OpenApiSchemas.PlatformSecretRevokeBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "browser_session_status_api_platform_connections__connection_id__browser_session_get": {
    method: "GET";
    path: "/api/platform-connections/{connection_id}/browser-session";
    pathParams: { "connection_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "import_browser_session_api_platform_connections__connection_id__browser_session_put": {
    method: "PUT";
    path: "/api/platform-connections/{connection_id}/browser-session";
    pathParams: { "connection_id": string };
    query: {  };
    body: OpenApiSchemas.BrowserStorageStateBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "probe_connection_api_platform_connections__connection_id__probe_post": {
    method: "POST";
    path: "/api/platform-connections/{connection_id}/probe";
    pathParams: { "connection_id": string };
    query: {  };
    body: OpenApiSchemas.ConnectionProbeBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "revoke_platform_secret_api_platform_connections__connection_id__secret_delete": {
    method: "DELETE";
    path: "/api/platform-connections/{connection_id}/secret";
    pathParams: { "connection_id": string };
    query: {  };
    body: OpenApiSchemas.PlatformSecretRevokeBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "rotate_platform_secret_api_platform_connections__connection_id__secret_put": {
    method: "PUT";
    path: "/api/platform-connections/{connection_id}/secret";
    pathParams: { "connection_id": string };
    query: {  };
    body: OpenApiSchemas.PlatformSecretWriteBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_platform_kinds_api_platform_kinds_get": {
    method: "GET";
    path: "/api/platform-kinds";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "list_platform_secrets_api_platform_secrets_get": {
    method: "GET";
    path: "/api/platform-secrets";
    pathParams: {  };
    query: { "connection_id"?: string };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "inspect_platform_secret_api_platform_secrets_inspect_get": {
    method: "GET";
    path: "/api/platform-secrets/inspect";
    pathParams: {  };
    query: { "reference": string };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_projects_api_projects_get": {
    method: "GET";
    path: "/api/projects";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "create_project_api_projects_post": {
    method: "POST";
    path: "/api/projects";
    pathParams: {  };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "update_project_api_projects__project_id__patch": {
    method: "PATCH";
    path: "/api/projects/{project_id}";
    pathParams: { "project_id": string };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "project_git_status_api_projects__project_id__git_get": {
    method: "GET";
    path: "/api/projects/{project_id}/git";
    pathParams: { "project_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "project_git_checkout_api_projects__project_id__git_checkout_post": {
    method: "POST";
    path: "/api/projects/{project_id}/git/checkout";
    pathParams: { "project_id": string };
    query: {  };
    body: OpenApiSchemas.ProjectGitCheckoutBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "project_git_worktrees_api_projects__project_id__git_worktrees_get": {
    method: "GET";
    path: "/api/projects/{project_id}/git/worktrees";
    pathParams: { "project_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "query_api_queries_post": {
    method: "POST";
    path: "/api/queries";
    pathParams: {  };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "readiness_api_readiness_get": {
    method: "GET";
    path: "/api/readiness";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "get_receipt_api_receipts__command_id__get": {
    method: "GET";
    path: "/api/receipts/{command_id}";
    pathParams: { "command_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "receipt_effects_api_receipts__command_id__effects_get": {
    method: "GET";
    path: "/api/receipts/{command_id}/effects";
    pathParams: { "command_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_runs_api_runs_get": {
    method: "GET";
    path: "/api/runs";
    pathParams: {  };
    query: { "archived"?: number };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "new_run_api_runs_post": {
    method: "POST";
    path: "/api/runs";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "delete_run_api_runs__run_id__delete": {
    method: "DELETE";
    path: "/api/runs/{run_id}";
    pathParams: { "run_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "update_run_api_runs__run_id__patch": {
    method: "PATCH";
    path: "/api/runs/{run_id}";
    pathParams: { "run_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "btw_api_runs__run_id__btw_post": {
    method: "POST";
    path: "/api/runs/{run_id}/btw";
    pathParams: { "run_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "control_api_runs__run_id__control_post": {
    method: "POST";
    path: "/api/runs/{run_id}/control";
    pathParams: { "run_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "control_receipt_api_runs__run_id__control__command_id__get": {
    method: "GET";
    path: "/api/runs/{run_id}/control/{command_id}";
    pathParams: { "run_id": string; "command_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "run_credentials_api_runs__run_id__credentials_get": {
    method: "GET";
    path: "/api/runs/{run_id}/credentials";
    pathParams: { "run_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "events_api_runs__run_id__events_get": {
    method: "GET";
    path: "/api/runs/{run_id}/events";
    pathParams: { "run_id": string };
    query: { "replay"?: string; "after"?: number };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "hitl_api_runs__run_id__hitl_post": {
    method: "POST";
    path: "/api/runs/{run_id}/hitl";
    pathParams: { "run_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "open_run_workspace_api_runs__run_id__open_post": {
    method: "POST";
    path: "/api/runs/{run_id}/open";
    pathParams: { "run_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "request_progress_api_runs__run_id__progress_post": {
    method: "POST";
    path: "/api/runs/{run_id}/progress";
    pathParams: { "run_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "resolve_run_api_runs__run_id__resolve_post": {
    method: "POST";
    path: "/api/runs/{run_id}/resolve";
    pathParams: { "run_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "start_run_api_runs__run_id__start_post": {
    method: "POST";
    path: "/api/runs/{run_id}/start";
    pathParams: { "run_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "upload_files_api_runs__run_id__uploads_post": {
    method: "POST";
    path: "/api/runs/{run_id}/uploads";
    pathParams: { "run_id": string };
    query: {  };
    body: OpenApiSchemas.Body_upload_files_api_runs__run_id__uploads_post;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "kill_worker_api_runs__run_id__workers_delete": {
    method: "DELETE";
    path: "/api/runs/{run_id}/workers";
    pathParams: { "run_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "spawn_worker_api_runs__run_id__workers_post": {
    method: "POST";
    path: "/api/runs/{run_id}/workers";
    pathParams: { "run_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_agent_engines_api_settings_agent_engines_get": {
    method: "GET";
    path: "/api/settings/agent-engines";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "list_credential_accounts_api_settings_credential_accounts_get": {
    method: "GET";
    path: "/api/settings/credential-accounts";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "delete_credential_account_api_settings_credential_accounts__account_id__delete": {
    method: "DELETE";
    path: "/api/settings/credential-accounts/{account_id}";
    pathParams: { "account_id": string };
    query: { "detach_references"?: boolean };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "put_credential_account_api_settings_credential_accounts__account_id__put": {
    method: "PUT";
    path: "/api/settings/credential-accounts/{account_id}";
    pathParams: { "account_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "import_host_codex_api_settings_credential_accounts__account_id__import_host_codex_post": {
    method: "POST";
    path: "/api/settings/credential-accounts/{account_id}/import-host-codex";
    pathParams: { "account_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "import_host_login_api_settings_credential_accounts__account_id__import_host_login_post": {
    method: "POST";
    path: "/api/settings/credential-accounts/{account_id}/import-host-login";
    pathParams: { "account_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "probe_credential_account_api_settings_credential_accounts__account_id__test_post": {
    method: "POST";
    path: "/api/settings/credential-accounts/{account_id}/test";
    pathParams: { "account_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "refresh_stale_credential_models_api_settings_credential_models_refresh_stale_post": {
    method: "POST";
    path: "/api/settings/credential-models/refresh-stale";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "list_credentials_api_settings_credentials_get": {
    method: "GET";
    path: "/api/settings/credentials";
    pathParams: {  };
    query: { "environment"?: string; "fresh"?: boolean };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "refresh_credential_models_api_settings_credentials__credential_id__models_refresh_post": {
    method: "POST";
    path: "/api/settings/credentials/{credential_id}/models/refresh";
    pathParams: { "credential_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "probe_credential_api_settings_credentials__credential_id__test_post": {
    method: "POST";
    path: "/api/settings/credentials/{credential_id}/test";
    pathParams: { "credential_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "put_identity_model_api_settings_identity_put": {
    method: "PUT";
    path: "/api/settings/identity";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "probe_llm_endpoint_route_api_settings_llm_test_post": {
    method: "POST";
    path: "/api/settings/llm/test";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "list_model_endpoint_connections_api_settings_model_endpoints_get": {
    method: "GET";
    path: "/api/settings/model-endpoints";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "create_model_endpoint_connection_api_settings_model_endpoints_post": {
    method: "POST";
    path: "/api/settings/model-endpoints";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "get_profiles_health_api_settings_profiles_health_get": {
    method: "GET";
    path: "/api/settings/profiles/health";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "probe_profile_health_api_settings_profiles__profile_id__health_post": {
    method: "POST";
    path: "/api/settings/profiles/{profile_id}/health";
    pathParams: { "profile_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "get_openvpn_config_api_settings_runtime_openvpn_get": {
    method: "GET";
    path: "/api/settings/runtime/openvpn";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "upload_openvpn_config_api_settings_runtime_openvpn_post": {
    method: "POST";
    path: "/api/settings/runtime/openvpn";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "get_system_login_api_settings_system_login_get": {
    method: "GET";
    path: "/api/settings/system-login";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "get_system_update_api_settings_system_update_get": {
    method: "GET";
    path: "/api/settings/system-update";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "check_system_update_api_settings_system_update_check_post": {
    method: "POST";
    path: "/api/settings/system-update/check";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "install_system_update_api_settings_system_update_install_post": {
    method: "POST";
    path: "/api/settings/system-update/install";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "rollback_system_update_api_settings_system_update_rollback_post": {
    method: "POST";
    path: "/api/settings/system-update/rollback";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "get_worker_image_api_settings_worker_image_get": {
    method: "GET";
    path: "/api/settings/worker-image";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "pull_worker_image_api_settings_worker_image_pull_post": {
    method: "POST";
    path: "/api/settings/worker-image/pull";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "probe_worker_model_api_settings_worker_model_test_post": {
    method: "POST";
    path: "/api/settings/worker-model/test";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "probe_worker_models_batch_api_settings_worker_model_test_batch_post": {
    method: "POST";
    path: "/api/settings/worker-model/test-batch";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "get_worker_model_test_results_api_settings_worker_model_test_results_get": {
    method: "GET";
    path: "/api/settings/worker-model/test-results";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "get_worker_models_api_settings_worker_models_get": {
    method: "GET";
    path: "/api/settings/worker-models";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "discover_worker_models_now_api_settings_worker_models_discover_post": {
    method: "POST";
    path: "/api/settings/worker-models/discover";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "get_worker_settings_api_settings_workers_get": {
    method: "GET";
    path: "/api/settings/workers";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "put_worker_settings_api_settings_workers_put": {
    method: "PUT";
    path: "/api/settings/workers";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "get_sidebar_preferences_api_sidebar_preferences_get": {
    method: "GET";
    path: "/api/sidebar-preferences";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "put_sidebar_preferences_api_sidebar_preferences_put": {
    method: "PUT";
    path: "/api/sidebar-preferences";
    pathParams: {  };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_threads_api_threads_get": {
    method: "GET";
    path: "/api/threads";
    pathParams: {  };
    query: { "project_id"?: string };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "create_thread_api_threads_post": {
    method: "POST";
    path: "/api/threads";
    pathParams: {  };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "inbox_events_api_threads_inbox_events_get": {
    method: "GET";
    path: "/api/threads/inbox/events";
    pathParams: {  };
    query: { "after"?: number; "snapshot"?: boolean; "project_id"?: string };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "search_threads_api_threads_search_get": {
    method: "GET";
    path: "/api/threads/search";
    pathParams: {  };
    query: { "q"?: string; "project_id"?: string; "include_archived"?: boolean; "include_superseded"?: boolean; "limit"?: number };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "get_thread_api_threads__thread_id__get": {
    method: "GET";
    path: "/api/threads/{thread_id}";
    pathParams: { "thread_id": string };
    query: { "mark_read"?: boolean; "messages_limit"?: string; "before_stream_seq"?: number | null; "after_stream_seq"?: number | null; "include_events"?: boolean; "include_superseded"?: boolean };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "read_artifact_api_threads__thread_id__artifacts__sha256__get": {
    method: "GET";
    path: "/api/threads/{thread_id}/artifacts/{sha256}";
    pathParams: { "thread_id": string; "sha256": string };
    query: { "download"?: boolean };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "post_command_api_threads__thread_id__commands_post": {
    method: "POST";
    path: "/api/threads/{thread_id}/commands";
    pathParams: { "thread_id": string };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "compact_thread_api_threads__thread_id__compact_post": {
    method: "POST";
    path: "/api/threads/{thread_id}/compact";
    pathParams: { "thread_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "thread_events_api_threads__thread_id__events_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/events";
    pathParams: { "thread_id": string };
    query: { "after"?: number; "snapshot"?: boolean };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "export_thread_api_threads__thread_id__export_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/export";
    pathParams: { "thread_id": string };
    query: { "format"?: string; "exclude_tools"?: number; "exclude_paths"?: number };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "thread_git_status_api_threads__thread_id__git_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/git";
    pathParams: { "thread_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "thread_git_checkout_api_threads__thread_id__git_checkout_post": {
    method: "POST";
    path: "/api/threads/{thread_id}/git/checkout";
    pathParams: { "thread_id": string };
    query: {  };
    body: OpenApiSchemas.ThreadGitCheckoutBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "impact_preview_api_threads__thread_id__impact_preview_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/impact-preview";
    pathParams: { "thread_id": string };
    query: { "turn_id": string; "mode"?: string; "text"?: string; "file_mode"?: string };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_memory_api_threads__thread_id__memory_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/memory";
    pathParams: { "thread_id": string };
    query: { "include_deleted"?: boolean; "q"?: string };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "record_memory_api_threads__thread_id__memory_post": {
    method: "POST";
    path: "/api/threads/{thread_id}/memory";
    pathParams: { "thread_id": string };
    query: {  };
    body: OpenApiSchemas.MemoryRecordBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "delete_memory_api_threads__thread_id__memory__memory_id__delete": {
    method: "DELETE";
    path: "/api/threads/{thread_id}/memory/{memory_id}";
    pathParams: { "thread_id": string; "memory_id": string };
    query: {  };
    body: OpenApiSchemas.MemoryDeleteBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "get_thread_messages_api_threads__thread_id__messages_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/messages";
    pathParams: { "thread_id": string };
    query: { "limit"?: string; "before_stream_seq"?: number | null; "after_stream_seq"?: number | null; "around_message_id"?: string | null };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "thread_pull_requests_api_threads__thread_id__pull_requests_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/pull-requests";
    pathParams: { "thread_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_shares_api_threads__thread_id__shares_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/shares";
    pathParams: { "thread_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "create_api_threads__thread_id__shares_post": {
    method: "POST";
    path: "/api/threads/{thread_id}/shares";
    pathParams: { "thread_id": string };
    query: {  };
    body: OpenApiSchemas.ShareCreateRequest;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "preview_api_threads__thread_id__shares_preview_post": {
    method: "POST";
    path: "/api/threads/{thread_id}/shares/preview";
    pathParams: { "thread_id": string };
    query: {  };
    body: OpenApiSchemas.SharePreviewRequest;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "source_api_threads__thread_id__shares_source_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/shares/source";
    pathParams: { "thread_id": string };
    query: { "offset"?: number };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "revoke_api_threads__thread_id__shares__share_id__delete": {
    method: "DELETE";
    path: "/api/threads/{thread_id}/shares/{share_id}";
    pathParams: { "thread_id": string; "share_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "get_turn_process_api_threads__thread_id__turns__turn_id__process_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/turns/{turn_id}/process";
    pathParams: { "thread_id": string; "turn_id": string };
    query: { "limit"?: number };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "upload_api_threads__thread_id__uploads_post": {
    method: "POST";
    path: "/api/threads/{thread_id}/uploads";
    pathParams: { "thread_id": string };
    query: { "kind"?: string };
    body: OpenApiSchemas.Body_upload_api_threads__thread_id__uploads_post;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "user_input_fixture_capture_api_threads__thread_id__user_input_fixture_capture_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/user-input-fixture-capture";
    pathParams: { "thread_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "workspace_diff_api_threads__thread_id__workspace_diff_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/workspace/diff";
    pathParams: { "thread_id": string };
    query: { "path"?: string; "staging"?: string };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "workspace_file_api_threads__thread_id__workspace_file_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/workspace/file";
    pathParams: { "thread_id": string };
    query: { "path": string; "line"?: number | null };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "workspace_file_raw_api_threads__thread_id__workspace_file_raw_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/workspace/file/raw";
    pathParams: { "thread_id": string };
    query: { "path": string; "download"?: boolean };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "workspace_files_api_threads__thread_id__workspace_files_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/workspace/files";
    pathParams: { "thread_id": string };
    query: { "path"?: string };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "workspace_search_content_api_threads__thread_id__workspace_search_content_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/workspace/search/content";
    pathParams: { "thread_id": string };
    query: { "q"?: string; "limit"?: number };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "workspace_search_files_api_threads__thread_id__workspace_search_files_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/workspace/search/files";
    pathParams: { "thread_id": string };
    query: { "q"?: string; "limit"?: number };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "workspace_terminal_api_threads__thread_id__workspace_terminal_post": {
    method: "POST";
    path: "/api/threads/{thread_id}/workspace/terminal";
    pathParams: { "thread_id": string };
    query: {  };
    body: OpenApiSchemas.WorkspaceCommandBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_terminal_sessions_api_threads__thread_id__workspace_terminal_sessions_get": {
    method: "GET";
    path: "/api/threads/{thread_id}/workspace/terminal/sessions";
    pathParams: { "thread_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "create_terminal_session_api_threads__thread_id__workspace_terminal_sessions_post": {
    method: "POST";
    path: "/api/threads/{thread_id}/workspace/terminal/sessions";
    pathParams: { "thread_id": string };
    query: {  };
    body: OpenApiSchemas.TerminalSessionCreateBody | null;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "close_terminal_session_api_threads__thread_id__workspace_terminal_sessions__session_id__delete": {
    method: "DELETE";
    path: "/api/threads/{thread_id}/workspace/terminal/sessions/{session_id}";
    pathParams: { "thread_id": string; "session_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "interrupt_terminal_session_api_threads__thread_id__workspace_terminal_sessions__session_id__interrupt_post": {
    method: "POST";
    path: "/api/threads/{thread_id}/workspace/terminal/sessions/{session_id}/interrupt";
    pathParams: { "thread_id": string; "session_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "usage_api_usage_get": {
    method: "GET";
    path: "/api/usage";
    pathParams: {  };
    query: { "start"?: number; "end"?: number | null; "run_id"?: string | null; "thread_id"?: string | null; "competition_id"?: string | null; "challenge_id"?: string | null; "model"?: string | null; "role"?: string | null; "workspace_kind"?: string | null; "generation"?: number | null; "offset"?: number; "limit"?: number };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "import_history_api_usage_import_history_post": {
    method: "POST";
    path: "/api/usage/import-history";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "get_quota_api_usage_quota_get": {
    method: "GET";
    path: "/api/usage/quota";
    pathParams: {  };
    query: {  };
    body: never;
    response: unknown;
  };
  "update_quota_api_usage_quota__credential_id__put": {
    method: "PUT";
    path: "/api/usage/quota/{credential_id}";
    pathParams: { "credential_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "refresh_quota_api_usage_quota__credential_id__refresh_post": {
    method: "POST";
    path: "/api/usage/quota/{credential_id}/refresh";
    pathParams: { "credential_id": string };
    query: {  };
    body: never;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "list_workspace_kinds_api_workspace_kinds_get": {
    method: "GET";
    path: "/api/workspace-kinds";
    pathParams: {  };
    query: {  };
    body: never;
    response: Array<OpenApiSchemas.WorkspaceKindInfo>;
  };
  "bind_workspace_api_workspaces_post": {
    method: "POST";
    path: "/api/workspaces";
    pathParams: {  };
    query: {  };
    body: { [key: string]: unknown };
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
  "delete_worktree_api_workspaces_delete_worktree_post": {
    method: "POST";
    path: "/api/workspaces/delete-worktree";
    pathParams: {  };
    query: {  };
    body: OpenApiSchemas.WorkspaceDeleteWorktreeBody;
    response: unknown | OpenApiSchemas.HTTPValidationError;
  };
}

export type OpenApiOperationId = keyof OpenApiOperations;
export type OpenApiOperation<K extends OpenApiOperationId> = OpenApiOperations[K];
