"""从平台契约 Pydantic 模型生成 JSON Schema 与 TypeScript 类型（CORE-01）。

用法::

    uv run python scripts/gen_contracts_ts.py           # 生成产物
    uv run python scripts/gen_contracts_ts.py --check   # 校验产物是否最新

产物（前端可直接 import）：

- ``apps/web/ui/lib/contracts/schema.json``：合并后的 JSON Schema（调试/核验用）
- ``apps/web/ui/lib/contracts/index.ts``：全部契约模型与枚举的 TS 类型

输出稳定：模型与枚举按 ``muteki.platform.contracts.CONTRACT_MODELS`` /
``CONTRACT_ENUMS`` 的固定顺序输出，字段保持 Pydantic 声明顺序，
schema.json 键排序。重复运行不产生 diff。
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from pydantic import BaseModel

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = REPO_ROOT / "apps" / "web" / "ui" / "lib" / "contracts"
TS_PATH = OUT_DIR / "index.ts"
SCHEMA_PATH = OUT_DIR / "schema.json"

HEADER = (
    "// Code generated by scripts/gen_contracts_ts.py from "
    "muteki/platform/contracts. DO NOT EDIT.\n"
    "// 手动修改会在下次生成时被覆盖；字段变更请改 Python 契约模型。\n"
)


def build_combined_schema() -> dict[str, Any]:
    """把所有契约模型与枚举合并成一份 ``$defs`` JSON Schema。"""
    from muteki.platform.contracts import CONTRACT_ENUMS, CONTRACT_MODELS

    defs: dict[str, Any] = {}
    for cls in [*CONTRACT_ENUMS, *CONTRACT_MODELS]:
        if issubclass(cls, BaseModel):
            schema = cls.model_json_schema(ref_template="#/$defs/{model}")
            nested = schema.pop("$defs", {})
            defs[cls.__name__] = schema
            defs.update(nested)
        else:  # str Enum
            defs[cls.__name__] = {
                "title": cls.__name__,
                "type": "string",
                "enum": [member.value for member in cls],
            }
    return {"$defs": dict(sorted(defs.items()))}


def _ts_type(node: dict[str, Any]) -> str:
    """把单个 JSON Schema 节点映射为 TS 类型。"""
    if not node:
        return "unknown"
    ref = node.get("$ref")
    if ref:
        return ref.rsplit("/", 1)[-1]
    if "anyOf" in node:
        parts = [_ts_type(part) for part in node["anyOf"]]
        # 去重并保持顺序，输出稳定的 union
        seen: list[str] = []
        for part in parts:
            if part not in seen:
                seen.append(part)
        return " | ".join(seen)
    if "enum" in node:
        return " | ".join(json.dumps(v, ensure_ascii=False) for v in node["enum"])
    if "const" in node:
        return json.dumps(node["const"], ensure_ascii=False)
    node_type = node.get("type")
    if isinstance(node_type, list):
        return " | ".join(_ts_type({**node, "type": t}) for t in node_type)
    if node_type == "string":
        return "string"  # date-time / binary 等 format 统一为 string
    if node_type in ("integer", "number"):
        return "number"
    if node_type == "boolean":
        return "boolean"
    if node_type == "null":
        return "null"
    if node_type == "array":
        return f"{_ts_type(node.get('items') or {})}[]"
    if node_type == "object":
        if "properties" in node:
            return _ts_object(node)
        return "Record<string, unknown>"
    return "unknown"


def _ts_object(schema: dict[str, Any]) -> str:
    required = set(schema.get("required") or [])
    lines = ["{"]
    for name, prop in (schema.get("properties") or {}).items():
        optional = "" if name in required else "?"
        lines.append(f"  {name}{optional}: {_ts_type(prop)};")
    lines.append("}")
    return "\n".join(lines)


def render_typescript(defs: dict[str, Any]) -> str:
    """按注册表固定顺序渲染 TS 类型文件。"""
    from muteki.platform.contracts import (
        CONTRACT_ENUMS,
        CONTRACT_MODELS,
        CONTRACT_SCHEMA_VERSION,
    )

    chunks = [HEADER, f"export const CONTRACTS_SCHEMA_VERSION = {CONTRACT_SCHEMA_VERSION};\n"]
    for enum_cls in CONTRACT_ENUMS:
        schema = defs[enum_cls.__name__]
        doc = _ts_doc(enum_cls)
        chunks.append(f"{doc}export type {enum_cls.__name__} = {_ts_type(schema)};\n")
    for model_cls in CONTRACT_MODELS:
        schema = defs[model_cls.__name__]
        doc = _ts_doc(model_cls)
        body = _ts_object(schema)
        chunks.append(f"{doc}export interface {model_cls.__name__} {body}\n")
    return "\n".join(chunks)


def _ts_doc(cls: type) -> str:
    """渲染 TS 文档注释；去掉 Python docstring 的 RST 标记与换行。"""
    doc = (cls.__doc__ or "").strip()
    if not doc:
        return ""
    summary = " ".join(doc.splitlines()[0].split()).replace("``", "")
    return f"/** {summary} */\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="只校验产物是否最新，不写文件")
    args = parser.parse_args(argv)

    combined = build_combined_schema()
    schema_text = json.dumps(combined, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    ts_text = render_typescript(combined["$defs"])

    if args.check:
        stale = []
        if not SCHEMA_PATH.exists() or SCHEMA_PATH.read_text() != schema_text:
            stale.append(str(SCHEMA_PATH))
        if not TS_PATH.exists() or TS_PATH.read_text() != ts_text:
            stale.append(str(TS_PATH))
        if stale:
            print("stale generated files:", *stale, sep="\n  ")
            return 1
        print("generated contracts are up to date")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    SCHEMA_PATH.write_text(schema_text)
    TS_PATH.write_text(ts_text)
    print(f"wrote {SCHEMA_PATH}")
    print(f"wrote {TS_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
