"""生成完整 Web OpenAPI 快照与前端 API 类型，并支持 CI 漂移检查。

用法::

    uv run python scripts/gen_openapi.py
    uv run python scripts/gen_openapi.py --check
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import os
import sys
import tempfile
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = REPO_ROOT / "apps" / "web" / "ui" / "lib" / "contracts"
OPENAPI_PATH = OUT_DIR / "openapi.json"
TS_PATH = OUT_DIR / "openapi.ts"


def build_openapi() -> dict[str, Any]:
    """从真实 FastAPI 装配生成 schema，并关闭临时产品服务。"""
    from apps.web.run_manager import RunManager
    from apps.web.server import create_app

    os.environ.setdefault("MUTEKI_WEB_BIND", "127.0.0.1")
    with tempfile.TemporaryDirectory(prefix="muteki-openapi-") as raw_root:
        root = Path(raw_root)
        manager = RunManager(
            sessions_root=root / "sessions",
            control_root=root / "control",
        )
        app = create_app(manager)
        schema = app.openapi()
        asyncio.run(app.state.platform_stack.shutdown())
    return schema


def _safe_name(value: str) -> str:
    text = "".join(ch if ch.isalnum() else "_" for ch in value)
    if text and text[0].isdigit():
        text = f"_{text}"
    return text or "Anonymous"


def _ts_type(schema: Any) -> str:
    if not isinstance(schema, dict) or not schema:
        return "unknown"
    ref = schema.get("$ref")
    if ref:
        return f"OpenApiSchemas.{_safe_name(str(ref).rsplit('/', 1)[-1])}"
    if "anyOf" in schema:
        return " | ".join(dict.fromkeys(_ts_type(item) for item in schema["anyOf"]))
    if "oneOf" in schema:
        return " | ".join(dict.fromkeys(_ts_type(item) for item in schema["oneOf"]))
    if "allOf" in schema:
        return " & ".join(dict.fromkeys(_ts_type(item) for item in schema["allOf"]))
    if "enum" in schema:
        return " | ".join(json.dumps(item, ensure_ascii=False) for item in schema["enum"])
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(_ts_type({**schema, "type": item}) for item in kind)
    if kind == "string":
        return "string"
    if kind in {"number", "integer"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        return f"Array<{_ts_type(schema.get('items'))}>"
    if kind == "object" or "properties" in schema:
        required = set(schema.get("required") or [])
        fields = []
        for name, field in sorted((schema.get("properties") or {}).items()):
            optional = "" if name in required else "?"
            fields.append(
                f"{json.dumps(name, ensure_ascii=False)}{optional}: {_ts_type(field)}"
            )
        if schema.get("additionalProperties"):
            fields.append("[key: string]: unknown")
        return "{ " + "; ".join(fields) + " }"
    return "unknown"


def _parameters(operation: dict[str, Any], location: str) -> str:
    fields = []
    for parameter in operation.get("parameters") or []:
        if parameter.get("in") != location:
            continue
        name = str(parameter.get("name") or "value")
        optional = "" if parameter.get("required") else "?"
        fields.append(
            f"{json.dumps(name, ensure_ascii=False)}{optional}: "
            f"{_ts_type(parameter.get('schema'))}"
        )
    return "{ " + "; ".join(fields) + " }"


def _body_type(operation: dict[str, Any]) -> str:
    content = (operation.get("requestBody") or {}).get("content") or {}
    for media_type in ("application/json", "multipart/form-data"):
        if media_type in content:
            return _ts_type(content[media_type].get("schema"))
    if content:
        return _ts_type(next(iter(content.values())).get("schema"))
    return "never"


def _response_type(operation: dict[str, Any]) -> str:
    variants: list[str] = []
    for response in (operation.get("responses") or {}).values():
        content = response.get("content") or {}
        if "application/json" in content:
            value = _ts_type(content["application/json"].get("schema"))
            if value not in variants:
                variants.append(value)
    return " | ".join(variants) if variants else "unknown"


def render_typescript(schema: dict[str, Any], digest: str) -> str:
    lines = [
        "// Code generated by scripts/gen_openapi.py. DO NOT EDIT.",
        f'export const OPENAPI_SHA256 = "{digest}" as const;',
        "",
        "export namespace OpenApiSchemas {",
    ]
    for name, body in sorted(
        ((schema.get("components") or {}).get("schemas") or {}).items()
    ):
        lines.append(f"  export type {_safe_name(name)} = {_ts_type(body)};")
    lines.extend(["}", "", "export interface OpenApiOperations {"])
    methods = {"get", "post", "put", "patch", "delete", "options", "head"}
    for path, path_item in sorted((schema.get("paths") or {}).items()):
        for method, operation in sorted(path_item.items()):
            if method not in methods or not isinstance(operation, dict):
                continue
            operation_id = str(operation.get("operationId") or f"{method}_{path}")
            lines.extend([
                f"  {json.dumps(operation_id)}: {{",
                f"    method: {json.dumps(method.upper())};",
                f"    path: {json.dumps(path)};",
                f"    pathParams: {_parameters(operation, 'path')};",
                f"    query: {_parameters(operation, 'query')};",
                f"    body: {_body_type(operation)};",
                f"    response: {_response_type(operation)};",
                "  };",
            ])
    lines.extend([
        "}",
        "",
        "export type OpenApiOperationId = keyof OpenApiOperations;",
        "export type OpenApiOperation<K extends OpenApiOperationId> = OpenApiOperations[K];",
        "",
    ])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    schema = build_openapi()
    openapi_text = json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    digest = hashlib.sha256(openapi_text.encode()).hexdigest()
    ts_text = render_typescript(schema, digest)
    outputs = {OPENAPI_PATH: openapi_text, TS_PATH: ts_text}
    if args.check:
        stale = [str(path) for path, text in outputs.items()
                 if not path.exists() or path.read_text() != text]
        if stale:
            print("stale generated files:", *stale, sep="\n  ")
            return 1
        print(f"generated OpenAPI is up to date ({digest})")
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, text in outputs.items():
        path.write_text(text)
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
