"""Public mixin façade for coordinator state, events, reports, and control."""

from muteki.swarm import coordinator_completion as _coord_completion
from muteki.swarm import coordinator_control as _coord_control
from muteki.swarm import coordinator_events as _coord_events
from muteki.swarm import coordinator_finalize as _coord_finalize
from muteki.swarm import coordinator_reports as _coord_reports
from muteki.swarm import coordinator_state as _coord_state


class _FlagsBusMixin:
    """Flag/bus/HITL façade. Method bodies live in split coordinator_* modules."""

_FlagsBusMixin._GRAPH_BRIDGE_KINDS = _coord_events._GRAPH_BRIDGE_KINDS
_FlagsBusMixin._build_solvers = _coord_state._build_solvers
_FlagsBusMixin._clean_review_policy = _coord_state._clean_review_policy
_FlagsBusMixin._clean_verifier_policy = _coord_state._clean_verifier_policy
_FlagsBusMixin._engine_healthcheck_cached = _coord_state._engine_healthcheck_cached
_FlagsBusMixin._reconcile_blackboard_skill = _coord_state._reconcile_blackboard_skill
_FlagsBusMixin._coverage_complete = _coord_completion._coverage_complete
_FlagsBusMixin._engagement = _coord_completion._engagement
_FlagsBusMixin._expected_findings = _coord_completion._expected_findings
_FlagsBusMixin._expected_flags = _coord_completion._expected_flags
_FlagsBusMixin._findings_complete = _coord_completion._findings_complete
_FlagsBusMixin._flags_complete = _coord_completion._flags_complete
_FlagsBusMixin._goal_satisfied = _coord_completion._goal_satisfied
_FlagsBusMixin._multi_flag = _coord_completion._multi_flag
_FlagsBusMixin._pentest_flag_required = _coord_completion._pentest_flag_required
_FlagsBusMixin._pentest_product = _coord_completion._pentest_product
_FlagsBusMixin._persist_accepted_collection = _coord_completion._persist_accepted_collection
_FlagsBusMixin._qualified_report_count = _coord_completion._qualified_report_count
_FlagsBusMixin._record_findings = _coord_completion._record_findings
_FlagsBusMixin._record_flags = _coord_completion._record_flags
_FlagsBusMixin._salvage_flags_from_evidence = _coord_completion._salvage_flags_from_evidence
_FlagsBusMixin._sync_findings_from_graph = _coord_completion._sync_findings_from_graph
_FlagsBusMixin._sync_flags_from_graph = _coord_completion._sync_flags_from_graph
_FlagsBusMixin._drain_report_pipeline = _coord_reports._drain_report_pipeline
_FlagsBusMixin._ensure_report_repro_intents = _coord_reports._ensure_report_repro_intents
_FlagsBusMixin._intent_matches_engagement = _coord_reports._intent_matches_engagement
_FlagsBusMixin._judge_pending_report_values = _coord_reports._judge_pending_report_values
_FlagsBusMixin._llm_value_judge = _coord_reports._llm_value_judge
_FlagsBusMixin._pentest_race_submission_quota_met = _coord_reports._pentest_race_submission_quota_met
_FlagsBusMixin._record_reports = _coord_reports._record_reports
_FlagsBusMixin._report_pipeline_pending = _coord_reports._report_pipeline_pending
_FlagsBusMixin._submitted_report_count = _coord_reports._submitted_report_count
_FlagsBusMixin._sync_reports_from_graph = _coord_reports._sync_reports_from_graph
_FlagsBusMixin._verifier_dispatch_items = _coord_reports._verifier_dispatch_items
_FlagsBusMixin._drain_graph_to_bus = _coord_events._drain_graph_to_bus
_FlagsBusMixin._emit_bb_bus = _coord_events._emit_bb_bus
_FlagsBusMixin._emit_finalize_lifecycle_deltas = _coord_events._emit_finalize_lifecycle_deltas
_FlagsBusMixin._emit_run_finished = _coord_events._emit_run_finished
_FlagsBusMixin._persist_runtime_diagnostics = _coord_events._persist_runtime_diagnostics
_FlagsBusMixin._graph_event_to_bb = _coord_events._graph_event_to_bb
_FlagsBusMixin._split_ids = _coord_events._split_ids
_FlagsBusMixin._cleanup_finished_worker_dirs = _coord_finalize._cleanup_finished_worker_dirs
_FlagsBusMixin._finalize_coordinator_run = _coord_finalize._finalize_coordinator_run
_FlagsBusMixin._retain_control_shutdown_owner = _coord_finalize._retain_control_shutdown_owner
_FlagsBusMixin.settle_control_shutdown = _coord_finalize.settle_control_shutdown
_FlagsBusMixin._ack_control = _coord_control._ack_control
_FlagsBusMixin._begin_operator_help_freeze = _coord_control._begin_operator_help_freeze
_FlagsBusMixin._contain_unfrozen_control_workers = _coord_control._contain_unfrozen_control_workers
_FlagsBusMixin._control_continuation_id = _coord_control._control_continuation_id
_FlagsBusMixin._control_paused_ids = _coord_control._control_paused_ids
_FlagsBusMixin._control_scope_parts = _coord_control._control_scope_parts
_FlagsBusMixin._control_target_solvers = _coord_control._control_target_solvers
_FlagsBusMixin._drain_hitl = _coord_control._drain_hitl
_FlagsBusMixin._end_operator_help_freeze = _coord_control._end_operator_help_freeze
_FlagsBusMixin._lease_scope_for_control = _coord_control._lease_scope_for_control
_FlagsBusMixin._materialize_reserved_control_text = _coord_control._materialize_reserved_control_text
_FlagsBusMixin._propose_control_continuation = _coord_control._propose_control_continuation
_FlagsBusMixin._reconcile_control_continuations = _coord_control._reconcile_control_continuations
_FlagsBusMixin._reconcile_standing_guidance = _coord_control._reconcile_standing_guidance
_FlagsBusMixin._resolve_control_text = _coord_control._resolve_control_text
_FlagsBusMixin._set_control_frozen = _coord_control._set_control_frozen
_FlagsBusMixin._supervise_control_drain = _coord_control._supervise_control_drain
