/**
 * Shared worker-identity helpers — engine, deterministic color, initials.
 *
 * Colour is keyed by engine and GENERATED by lib/palette-engine (fixed OKLCH
 * hue per engine, mode-correct lightness/chroma): the same worker reads as
 * the same saturated hue in every color scheme, in both light and dark mode.
 * No hex lives here — ENGINE_HUE in palette-engine.ts is the single source.
 */

import { ENGINE_HUE, currentMode, hueColor } from "./palette-engine";

/** Engine ids the operator can pick when adding a worker to a live run. */
export const SPAWN_ENGINES = [
  "claude", "codex", "cursor", "pi", "omp", "kimi", "grok", "opencode", "devin",
] as const;

// neutral slate for unknown workers — a whisper of chroma, deliberately quiet.
const defaultColor = (): string => hueColor(250, currentMode(), 0.18);

// pi/omp match on whole -/_/: segments only: a substring test would misfire on
// "cursor-API-container" (contains "pi") and similar ids.
const engineSegment = (s: string): string => {
  const segs = s.split(/[-_:]/);
  if (segs.includes("pi")) return "pi";
  if (segs.includes("omp") || segs.includes("ohmypi")) return "omp";
  return "";
};

export function workerEngine(id: string, engine?: string): string {
  const s = (engine || id).toLowerCase();
  if (s === "claude_code" || s === "claude") return "Claude Code";
  if (s === "codex_cli" || s === "codex") return "Codex";
  if (s === "cursor_agent" || s === "cursor") return "Cursor";
  if (s === "kimi_code" || s === "kimi" || s === "kimi-code") return "Kimi Code";
  if (s === "grok_cli" || s === "grok") return "Grok";
  if (s === "opencode_cli" || s === "opencode") return "OpenCode";
  if (s === "devin_cli" || s === "devin") return "Devin CLI";
  if (s === "dsh_sdk_worker" || s === "dsh" || s === "deepseek_harness") return "DeepSeek Harness";
  if (s === "pi" || s === "omp" || s === "oh_my_pi" || s === "oh-my-pi" || s === "ohmypi") {
    return s === "pi" ? "Pi" : "Oh My Pi";
  }
  const seg = engineSegment(s);
  if (seg === "pi") return "Pi";
  if (seg === "omp") return "Oh My Pi";
  if (s.includes("codex")) return "Codex";
  if (s.includes("cursor")) return "Cursor";
  if (s.includes("claude")) return "Claude Code";
  if (s.includes("kimi")) return "Kimi Code";
  if (s.includes("grok")) return "Grok";
  if (s.includes("opencode")) return "OpenCode";
  if (s.includes("devin")) return "Devin CLI";
  if (s.includes("dsh") || s.includes("deepseek-harness")) return "DeepSeek Harness";
  if (s.includes("deepseek") || s === "reason") return "DeepSeek";
  if (s.includes("mock")) return "Mock";
  if (s.includes("verifier")) return "Verifier";
  return "Worker";
}

/** The ENGINE_HUE / EngineLogo key a worker resolves to; "" when unknown. */
export function workerEngineKey(id: string, engine?: string): string {
  const s = (engine || id).toLowerCase();
  if (s === "claude_code") return "claude";
  if (s === "codex_cli") return "codex";
  if (s === "cursor_agent") return "cursor";
  const seg = engineSegment(s);
  if (seg) return seg;
  for (const k of Object.keys(ENGINE_HUE)) {
    if (k === "pi" || k === "omp") continue; // substring-unsafe; segment-matched above
    if (s.includes(k)) return k;
  }
  return "";
}

export function workerColor(id: string, engine?: string): string {
  const key = workerEngineKey(id, engine);
  return key ? hueColor(ENGINE_HUE[key], currentMode()) : defaultColor();
}

/**
 * CSS-variable form of workerColor. It resolves in the stylesheet, so it
 * follows a theme switch without a re-render and never touches
 * getComputedStyle; base.css carries the static fallbacks and palette-engine
 * regenerates the --eng-* tokens on load.
 */
export function workerColorVar(id: string, engine?: string): string {
  const key = workerEngineKey(id, engine);
  return key ? `var(--eng-${key}, var(--blue))` : "var(--eng-default)";
}

export function workerInitial(id: string): string {
  const tail = id.split(/[-_:]/).filter(Boolean).pop() || id;
  return tail.slice(0, 2).toUpperCase();
}

// workerGeneration lives in ./events (the dependency-free event contract) and
// is re-exported here for worker-identity consumers.
export { workerGeneration } from "./events";

function workerShortLabel(id: string, engine?: string): string {
  const raw = (id || "").toLowerCase();
  if (raw === "reason" || raw === "solver" || raw === "coordinator") return raw;
  const resolved = workerEngine(id, engine);
  const base = resolved === "Claude Code" ? "claude"
    : resolved === "Oh My Pi" ? "omp"
    : resolved === "Worker" ? (id.split(/[:]/).pop() || id).replace(/^cli-/, "")
    : resolved.toLowerCase().replace(/\s+/g, "-");
  // Generation-aware ids (cli-pi-2-g2): strip the -gN tail for the numeric
  // suffix parse, then re-attach it so the label stays generation-readable.
  const gen = id.match(/-g(\d+)$/)?.[1];
  const stem = gen ? id.slice(0, -(`-g${gen}`.length)) : id;
  const suffix = stem.match(/[-_:](\d+)$/)?.[1];
  const core = suffix ? `${base.replace(/-\d+$/, "")}-${suffix}` : base;
  return gen ? `${core}·g${gen}` : core;
}

export type WorkerConnectionKind = "official" | "custom_endpoint" | "system";

export type WorkerIdentity = {
  solverId: string;
  engine?: string;
  profileId?: string;
  profileLabel?: string;
  model?: string;
  accountId?: string;
  endpointHost?: string;
  connection?: WorkerConnectionKind;
  provider?: string;
};

export type WorkerDisplayName = {
  title: string;
  initial: string;
  titleAttr: string;
  model?: string;
  connectionKind?: WorkerConnectionKind;
  connectionDetail?: string;
};

function workerInitialFromLabel(label: string, fallbackId: string): string {
  const text = (label || "").trim();
  if (!text) return workerInitial(fallbackId);
  if (/[\u3400-\u9fff]/.test(text)) return text.slice(0, 2);
  const parts = text.split(/[\s\-_:/]+/).filter(Boolean);
  if (parts.length >= 2) return (parts[0][0] + parts[1][0]).toUpperCase();
  return text.slice(0, 2).toUpperCase();
}

function workerIdentityKey(lane: WorkerIdentity): string {
  return lane.profileId || lane.profileLabel || lane.solverId;
}

function workerInstanceIndex(
  id: string,
  siblings: WorkerIdentity[],
): { index: number; count: number } {
  const self = siblings.find((lane) => lane.solverId === id);
  const key = self ? workerIdentityKey(self) : id;
  const group = siblings.filter((lane) => workerIdentityKey(lane) === key);
  const index = Math.max(1, group.findIndex((lane) => lane.solverId === id) + 1);
  return { index, count: group.length };
}

export function toWorkerIdentity(
  id: string,
  lane?: {
    engine?: string;
    profileId?: string;
    profileLabel?: string;
    model?: string;
    accountId?: string;
    endpointHost?: string;
    connection?: WorkerConnectionKind;
    provider?: string;
  } | null,
): WorkerIdentity {
  return {
    solverId: id,
    engine: lane?.engine,
    profileId: lane?.profileId,
    profileLabel: lane?.profileLabel,
    model: lane?.model,
    accountId: lane?.accountId,
    endpointHost: lane?.endpointHost,
    connection: lane?.connection,
    provider: lane?.provider,
  };
}

export function workerDisplayName(
  id: string,
  lane?: WorkerIdentity | null,
  siblings: WorkerIdentity[] = [],
): WorkerDisplayName {
  const identity = lane ? { ...lane, solverId: lane.solverId || id } : { solverId: id };
  const baseTitle = (identity.profileLabel || "").trim() || workerShortLabel(id, identity.engine);
  const group = siblings.length ? siblings : [identity];
  const { index, count } = workerInstanceIndex(id, group);
  const title = count > 1 && index > 1 ? `${baseTitle} · ${index}` : baseTitle;
  const connectionDetail = identity.connection === "custom_endpoint"
    ? (identity.provider || identity.endpointHost || "")
    : identity.connection === "official"
      ? (identity.accountId || "")
      : identity.connection === "system"
        ? ""
        : (identity.provider || identity.endpointHost || identity.accountId || "");
  return {
    title,
    initial: workerInitialFromLabel(baseTitle, id),
    titleAttr: [id, identity.model, connectionDetail].filter(Boolean).join(" · "),
    model: identity.model,
    connectionKind: identity.connection,
    connectionDetail,
  };
}

export function formatWorkerSubtitle(
  display: WorkerDisplayName,
  t: (key: string) => string,
): string {
  const model = display.model || t("runtime.actor.defaultModel");
  const kind = display.connectionKind;
  let connection = display.connectionDetail || "";
  if (kind) {
    switch (kind) {
      case "custom_endpoint":
        connection = display.connectionDetail || t("runtime.actor.customEndpoint");
        break;
      case "official":
        connection = display.connectionDetail || t("runtime.actor.officialAccount");
        break;
      case "system":
        connection = t("runtime.actor.systemLogin");
        break;
      default: {
        const _exhaustive: never = kind;
        return _exhaustive;
      }
    }
  }
  return connection ? `${model} · ${connection}` : model;
}

export function actorDisplayTitle(
  id: string,
  t: (key: string) => string,
  lane?: WorkerIdentity | null,
  siblings: WorkerIdentity[] = [],
): string {
  // "operator" is the collaboration model's fixed id for the human (OPERATOR_ID).
  if (id === "human" || id === "operator") return t("runtime.actor.operator");
  if (id === "system") return t("runtime.actor.system");
  if (id === "report-value") return t("runtime.actor.reportValue");
  if (id === "reason" || id === "coordinator") return t("coord.title");
  return workerDisplayName(id, lane, siblings).title;
}

/** The resume/attach command for a live CLI session, by engine. */
export function resumeCommand(engine: string, session: string): string {
  if (!session) return "";
  const resolved = workerEngine(engine, engine);
  if (resolved === "Codex") return `codex exec resume ${session}`;
  if (resolved === "Cursor") return `cursor-agent --resume ${session}`;
  if (resolved === "Pi") return `pi --session ${session}`;
  if (resolved === "Oh My Pi") return `omp --resume ${session}`;
  if (resolved === "Kimi Code") return `kimi --session ${session}`;
  if (resolved === "Grok") return `grok --resume ${session}`;
  if (resolved === "OpenCode") return `opencode run --session ${session}`;
  if (resolved === "Devin CLI") return `devin --resume ${session}`;
  if (resolved === "DeepSeek Harness") return "";
  return `claude -r ${session}`;
}
