const http = require('node:http');

// A disposable Web app fixture. Desktop tests must retain this page's own
// sidebar, form, state and handlers while relocating only its global chrome.
function createFixture() {
  const server = http.createServer((request, response) => {
    response.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
    response.end(`<!doctype html><html lang="zh-CN" data-theme="light"><head><title>Muteki Web fixture</title><style>
    *{box-sizing:border-box}html,body{height:100%;margin:0;font:14px -apple-system,sans-serif;color:#262626;background:white}body{--rail:#f8f8f8;--line:#e8e8e8}.workspace-frame{height:100%;display:flex;flex-direction:column;--workspace-nav-height:58px;--conv-sidebar-width:270px;--workspace-collapsed-brand-height:52px}.workspace-nav{height:58px;border-bottom:1px solid #eee;display:flex;align-items:center;justify-content:center;gap:22px}nav a{margin-right:25px;color:inherit}.workspace-shared-brand-dock{position:absolute;top:0;left:0;width:270px;height:58px;display:flex;align-items:center;justify-content:space-between;padding:0 20px;font-weight:600;font-size:19px}.workspace-nav-settings{display:flex;gap:8px}.workspace-frame-content{flex:1;min-height:0;display:flex}.cx-sidebar-nav{width:270px;flex-shrink:0;background:#f8f8f8;border-right:1px solid #eee;display:flex;flex-direction:column}.cx-sidebar-nav::before{content:'';height:0;flex:none}.sidebar-body{padding:18px 16px;line-height:2.5}.sidebar-body a{display:block;color:inherit;text-decoration:none;padding-left:12px}.sidebar-body strong{display:block;font-weight:500;margin-top:18px}.business{flex:1;min-width:0;display:flex;flex-direction:column;padding:30px 40px 18px}.business-content{flex:1;overflow:auto;max-width:760px;width:100%;margin:auto}h1{font-size:24px;font-weight:500;margin:15px 0 22px}p{line-height:1.9}button,input,textarea{font:inherit}button{cursor:pointer;border:1px solid #ddd;border-radius:7px;padding:7px 12px;background:white}.composer{max-width:760px;width:100%;margin:24px auto 0;border:1px solid #e5e5e5;border-radius:18px;padding:15px;box-shadow:0 5px 24px #00000008}.composer textarea{width:100%;height:68px;border:0;resize:none;outline:none;background:transparent}.composer footer{display:flex;justify-content:space-between;align-items:center;color:#888;font-size:12px}.composer button{border-radius:20px;background:#377bea;color:white;border:0}dialog{border:1px solid #ddd;border-radius:14px;padding:24px;width:430px}dialog::backdrop{background:#0003}dialog input{width:100%;padding:12px;border:1px solid #ddd;border-radius:7px;margin:10px 0 20px}.mode-card{border:1px solid #eee;border-radius:12px;padding:20px;margin:20px 0}.badge{color:#888}.workspace-nav-badge{font-size:10px;padding:2px 4px;background:#e7f0ff;border-radius:10px}.dark{background:#191b20;color:#e8e8e8}.dark .business,.dark .workspace-frame{background:#191b20;color:#e8e8e8}.dark .cx-sidebar-nav{background:#22242a;color:#eee}.dark button{background:#292d34;color:#eee}.dark textarea{color:#eee}.dark .composer{border-color:#35383e}
    </style></head><body><div class="workspace-frame" data-conversation-layout="true" data-conversation-sidebar-collapsed="false"><div class="workspace-shared-brand-dock"><a href="/" style="color:inherit;text-decoration:none">Muteki</a><button class="workspace-brand-sidebar-toggle" aria-label="切换原有会话导航">☰</button></div><header class="workspace-nav"><nav id="workspace-navigation"><a href="/chat"><strong>对话</strong></a><a href="/task"><strong>单题</strong></a><a href="/competitions"><strong>比赛</strong><b class="workspace-nav-badge">2</b></a></nav><div class="workspace-nav-settings"><a class="workspace-nav-usage" href="/usage">用量</a><button class="workspace-nav-theme-toggle">切换主题</button><a class="workspace-nav-settings-gear" href="/settings/agents">设置</a><button class="workspace-nav-command">全局搜索</button></div></header><div class="workspace-frame-content"><aside class="cx-sidebar-nav"><div class="sidebar-body"><button id="new-chat">新聊天</button><strong>项目</strong><a href="/chat/example">桌面端导航布局</a><a href="/chat/files">整理工作目录</a><a href="/chat/notes">记录界面改进</a><strong>最近</strong><a href="/chat/recent">上一次会话</a></div></aside><main class="business" data-original-business="true"><div class="business-content"><h1 id="page-title"></h1><p id="page-description"></p><div class="mode-card"><strong>原有 Web 业务页面</strong><p>桌面端保留页面自己的列表、表单与状态，仅把全局导航移到最左侧。此处为本地测试内容，不会启动真实任务。</p><p id="path"></p><button id="preview">打开原有附件预览</button></div></div><div class="composer"><textarea id="original-composer" aria-label="原有页面输入框" placeholder="这里是业务页面自己的输入框…"></textarea><footer><span>原有业务操作</span><button id="save-draft">保存测试草稿</button></footer></div></main></div></div><dialog id="search"><h2>原有全局搜索</h2><input aria-label="搜索工作区" placeholder="搜索工作区、设置或最近任务"><button id="close-search">关闭</button></dialog><script>
    localStorage.setItem('muteki.workspace.solveOnly','0');
    const frame=document.querySelector('.workspace-frame');
    function render(){const path=location.pathname;const chat=path.startsWith('/chat');frame.dataset.conversationLayout=chat?'true':'false';document.querySelector('.cx-sidebar-nav').style.display=chat&&frame.dataset.conversationSidebarCollapsed!=='true'?'flex':'none';document.getElementById('page-title').textContent=chat?'对话':path.startsWith('/task')?'单题工作区':path.startsWith('/competitions')?'比赛工作区':path.startsWith('/usage')?'全局用量':path.startsWith('/settings')?'设置':'工作区';document.getElementById('page-description').textContent='页面内容与行为来自同一个 Web 服务。';document.getElementById('path').textContent='当前路由：'+path;document.getElementById('original-composer').value=localStorage.getItem('fixture-draft:'+path)||'';document.querySelectorAll('#workspace-navigation a').forEach(a=>a.classList.toggle('active',path.startsWith(a.pathname)));}
    document.addEventListener('click',event=>{const a=event.target.closest('a');if(a&&a.origin===location.origin){event.preventDefault();localStorage.setItem('fixture-draft:'+location.pathname,document.getElementById('original-composer').value);history.pushState({},'',a.href);render();}});window.onpopstate=render;
    document.querySelector('.workspace-nav-theme-toggle').onclick=()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';document.body.classList.toggle('dark',dark)};
    document.querySelector('.workspace-nav-command').onclick=()=>document.getElementById('search').showModal();document.getElementById('close-search').onclick=()=>document.getElementById('search').close();
    document.querySelector('.workspace-brand-sidebar-toggle').onclick=()=>{frame.dataset.conversationSidebarCollapsed=frame.dataset.conversationSidebarCollapsed==='true'?'false':'true';render()};
    document.getElementById('save-draft').onclick=()=>localStorage.setItem('fixture-draft:'+location.pathname,document.getElementById('original-composer').value);
    document.getElementById('new-chat').onclick=()=>{history.pushState({},'','/chat');render()};
    document.getElementById('preview').onclick=()=>{const child=window.open('about:blank');child.opener=null;child.location.replace(URL.createObjectURL(new Blob(['<h1>原有附件预览</h1>'],{type:'text/html'})))};
    render();
    </script></body></html>`);
  });
  return new Promise(resolve => server.listen(0, '127.0.0.1', () => resolve({ server, origin: `http://127.0.0.1:${server.address().port}`, close: async () => { server.closeAllConnections(); await new Promise(done => server.close(done)); } })));
}
module.exports = { createFixture };
